share/ruby-build/mruby-1.1.0

See the [annoucement](http://www.mruby.org/releases/2014/11/19/mruby-1.1.0-released.html).

mruby 1.1.0 was released

---

share/ruby-build/jruby-9.0.0.0-pre1

Sorry for the typo, my fault. I overlooked it :(

Fix JRuby 9.0.0.0-pre1 definition

---

share/ruby-build/rbx-2.5.1

add support for newly released rbx-2.5.1

add rbx-2.5.1

---

share/ruby-build/rbx-2.5.2

Add install support for Rubinius 2.5.2

add rbx-2.5.2

---

share/ruby-build/2.0.0-p643

We released new version of Ruby 2.0.0. see https://www.ruby-lang.org/en/news/2015/02/25/ruby-2-0-0-p643-is-released/

added definition of ruby 2.0.0-p643

---

share/ruby-build/2.2.1

see https://www.ruby-lang.org/en/news/2015/03/03/ruby-2-2-1-released/

added definition of Ruby 2.2.1

---

share/ruby-build/rbx-2.5.5

This PR will add rbx-2.5.5 to master branch.
Release Note: https://github.com/rubinius/rubinius/releases/tag/v2.5.5
Thank you in advance!

Add rbx-2.5.5

---

share/ruby-build/jruby-1.7.20.1

Add JRuby 1.7.20.1

---

share/ruby-build/2.3.0-preview1

Just came out today: https://gist.github.com/nurse/f95ead4fc08b5a454e12

Add MRI Ruby 2.3.0-preview1

---

share/ruby-build/jruby-9.0.4.0

:gem: http://lists.ruby-lang.org/pipermail/jruby/2015-November/000174.html

Added definition of latest jruby

---

README.md

Change github repo names to "rbenv" on README.md.

Change github repo names to rbenv.

---

share/ruby-build/2.3.0-preview2

See. http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/72045

Added definition of 2.3.0-preview2

---

share/ruby-build/2.0.0-p648
share/ruby-build/2.1.8
share/ruby-build/2.2.4

See
* https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-1-8-released/
* https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-2-4-released/

added definition of 2.1.8 and 2.2.4

---

share/ruby-build/mruby-1.2.0

Release:
https://github.com/mruby/mruby/releases/tag/1.2.0
Announcements:
http://www.mruby.org/releases/2015/11/18/mruby-1.2.0-released.html

Add mruby 1.2.0

---

test/cache.bats
test/checksum.bats
test/mirror.bats

And separate test body into arrange-act-assert blocks via newlines
Extracted from #881

Leverage assert_success helper

---

script/brew-publish

Explicitly specify destination refspec

---

share/ruby-build/rbx-3.10.0
share/ruby-build/rbx-3.11.0
share/ruby-build/rbx-3.12.0
share/ruby-build/rbx-3.13.0
share/ruby-build/rbx-3.14.0
share/ruby-build/rbx-3.6.0
share/ruby-build/rbx-3.7.0
share/ruby-build/rbx-3.8.0
share/ruby-build/rbx-3.9.0

I'm not sure if these commits are still welcome here after this debate #862.

Add Rubinius 3.6--3.14

---

share/ruby-build/rbx-2.71828182

scraped via [ruby-build-update-defs](https://github.com/jasonkarns/ruby-build-update-defs) plugin

add rbx-2.71828182

---

share/ruby-build/jruby-9.1.0.0-dev

https://twitter.com/jruby/status/703343625095221248

Add JRuby 9.1.0.0 snapshots

---

share/ruby-build/2.2.5
share/ruby-build/2.3.1

* https://www.ruby-lang.org/en/news/2016/04/26/ruby-2-2-5-released/
* https://www.ruby-lang.org/en/news/2016/04/26/ruby-2-3-1-released/

added definitions of 2.2.5 and 2.3.1

---

share/ruby-build/rbx-3.47

Add Rubinius 3.47

---

share/ruby-build/jruby-9.1.4.0

http://jruby.org/2016/09/01/jruby-9-1-4-0.html

Add JRuby 9.1.4.0

---

share/ruby-build/jruby-9.1.5.0

http://jruby.org/2016/09/06/jruby-9-1-5-0.html

Add Jruby 9.1.5.0

---

share/ruby-build/ree-1.8.7-2011.03
share/ruby-build/ree-1.8.7-2011.12
share/ruby-build/ree-1.8.7-2012.01
share/ruby-build/ree-1.8.7-2012.02

Use google code archive urls for REE, Fixed #991

---

script/brew-publish

To use official "pull-request" tool of homebrew
ref. https://github.com/rbenv/ruby-build/issues/980

Use bump formula pr

---

share/ruby-build/jruby-9.1.6.0

http://jruby.org/2016/11/09/jruby-9-1-6-0.html

Add JRuby 9.1.6.0

---

bin/rbenv-uninstall

```
$ rbenv uninstall 2.3.2
rbenv: remove /path/to/.rbenv/versions/2.3.2?
$
```
I don't know what I should type
and uninstallation is whether success or not.
I think this should be add kindly text like below.
```
$ rbenv uninstall 2.3.2
rbenv: remove /path/to/.rbenv/versions/2.3.2? [yN] 
Successfully uninstalled /path/to/.rbenv/versions/2.3.2
```

* bin/rbenv-uninstall: add kindly text into prompt

---

share/ruby-build/2.4.0-rc1

See the release announcement: https://www.ruby-lang.org/en/news/2016/12/11/ruby-2-4-0-rc1-released/

Add Ruby 2.4.0-rc1 definition

---

script/brew-publish
script/release
test/build.bats
test/test_helper.bash

I fixed to run all tests have been passed on FreeBSD 11-R.
I think it is useful for future development of ruby-build.
Will you merge this PR ?

Run test on freebsd

---

share/ruby-build/2.4.0

http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/78822

added definition for Ruby 2.4.0

---

bin/ruby-build

Inconsistent formatting was added as part of #1015

formatting: spaces for indentation

---

share/ruby-build/jruby-9.1.7.0

http://jruby.org/2017/01/11/jruby-9-1-7-0.html

Add JRuby 9.1.7.0

---

share/ruby-build/jruby-9.1.8.0

http://jruby.org/2017/03/06/jruby-9-1-8-0

Add jruby-9.1.8.0 support

---

bin/ruby-build
share/ruby-build/rbx-3.66
share/ruby-build/rbx-3.67
share/ruby-build/rbx-3.68
share/ruby-build/rbx-3.69

Fix instruction message and use llvm@3.7 for rbx build

---

share/ruby-build/2.4.1

Refer: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/80279

Add definition for Ruby 2.4.1

---

share/ruby-build/2.2.7

Refer: https://www.ruby-lang.org/en/news/2017/03/28/ruby-2-2-7-released

Add definition for Ruby 2.2.7

---

share/ruby-build/2.3.4

Refer: https://www.ruby-lang.org/en/news/2017/03/30/ruby-2-3-4-released

Add definition for Ruby 2.3.4

---

bin/ruby-build

Seems like we should add some "auto-bump-version" script ☺️

ruby-build 20170405

---

share/ruby-build/jruby-9.1.9.0

http://jruby.org/2017/05/16/jruby-9-1-9-0.html

Add jruby-9.1.9.0

---

share/ruby-build/jruby-9.1.10.0

http://jruby.org/2017/05/25/jruby-9-1-10-0.html

Add definition for JRuby 9.1.10.0

---

share/ruby-build/jruby-9.1.11.0
share/ruby-build/jruby-9.1.12.0

These JRubies has been released.
- http://jruby.org/2017/06/14/jruby-9-1-11-0.html
- http://jruby.org/2017/06/15/jruby-9-1-12-0.html
Thanks.

Add definition for JRuby 9.1.11.0 and 9.1.12.0

---

share/ruby-build/mruby-1.3.0

Release:
https://github.com/mruby/mruby/releases/tag/1.3.0
Announcementns:
http://mruby.org/releases/2017/07/04/mruby-1.3.0-released.html

Add mruby 1.3.0

---

share/ruby-build/2.6.0-dev

https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?revision=61474&view=revision

Ruby 2.6.0 development has started.

---

share/ruby-build/mruby-1.4.0
share/ruby-build/mruby-1.4.1

Release:
* https://github.com/mruby/mruby/releases/tag/1.4.0
* https://github.com/mruby/mruby/releases/tag/1.4.1
Announcements:
* http://mruby.org/releases/2018/04/27/mruby-1.4.1-released.html
(I searched but there seems to be no release announcement for 1.4.0.)

Add mruby 1.4.0 and mruby 1.4.1

---

share/ruby-build/truffleruby-1.0.0-rc2
share/ruby-build/truffleruby-1.0.0-rc3
share/ruby-build/truffleruby-1.0.0-rc5

Fix missing space since openssl-1.1.0i update

---

share/ruby-build/truffleruby-1.0.0-rc6

Add definition for TruffleRuby 1.0.0-rc6

---

share/ruby-build/2.3.8
share/ruby-build/2.4.5
share/ruby-build/2.5.2

https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-3-8-released/
https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-4-5-released/
https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-5-2-released/

add MRI 2.5.2, 2.4.5 and 2.3.8

---

share/ruby-build/2.7.0-dev

Ruby 2.7.0 development has started.
https://github.com/ruby/ruby/commit/3a0471faa0d383392ba05b3a6409b973b7b009d1

Add definition for Ruby 2.7.0-dev

---

script/update-truffleruby

Add script to generate a definition for TruffleRuby

---

share/ruby-build/2.6.1

Ruby 2.6.1 has been released.
https://github.com/ruby/www.ruby-lang.org/pull/1953

Add definition for Ruby 2.6.1

---

share/ruby-build/truffleruby-1.0.0-rc13

Add TruffleRuby 1.0.0-rc13

---

share/ruby-build/truffleruby-1.0.0-rc14

Add TruffleRuby 1.0.0-rc14.

---

share/ruby-build/truffleruby-1.0.0-rc15

Add TruffleRuby 1.0.0-rc15.

---

script/update-truffleruby
share/ruby-build/truffleruby-1.0.0-rc16

cc @hsbt 
See https://twitter.com/eregontp/status/1119266947269582849

Add TruffleRuby 1.0.0-rc16

---

script/update-truffleruby
share/ruby-build/truffleruby-19.0.0

cc @hsbt
FYI, this our first release. The naming scheme switched from 1.0.0 to something based on the year.

Add TruffleRuby 19.0.0

---

share/ruby-build/truffleruby-19.1.0

Add TruffleRuby 19.1.0

---

share/ruby-build/truffleruby-19.2.0

Add TruffleRuby 19.2.0

---

share/ruby-build/truffleruby-19.2.0.1

https://github.com/oracle/truffleruby/releases/tag/vm-19.2.0.1
cc @hsbt

Add TruffleRuby 19.2.0.1

---

share/ruby-build/jruby-9.2.9.0

Hi guys! jRuby latests release is out!
https://www.jruby.org/2019/10/30/jruby-9-2-9-0.html

Add definition for jruby 9 2 9 0

---

share/ruby-build/2.5.0
share/ruby-build/2.5.0-dev
share/ruby-build/2.5.0-preview1
share/ruby-build/2.5.0-rc1
share/ruby-build/2.5.1
share/ruby-build/2.5.2
share/ruby-build/2.5.3
share/ruby-build/2.5.4
share/ruby-build/2.5.5
share/ruby-build/2.5.6
share/ruby-build/2.6.0
share/ruby-build/2.6.0-dev
share/ruby-build/2.6.0-preview1
share/ruby-build/2.6.0-preview2
share/ruby-build/2.6.0-preview3
share/ruby-build/2.6.0-rc1
share/ruby-build/2.6.0-rc2
share/ruby-build/2.6.1
share/ruby-build/2.6.2
share/ruby-build/2.6.3
share/ruby-build/2.6.4
share/ruby-build/2.7.0-dev
share/ruby-build/2.7.0-preview1
share/ruby-build/truffleruby-19.0.0
share/ruby-build/truffleruby-19.1.0
share/ruby-build/truffleruby-19.2.0
share/ruby-build/truffleruby-19.2.0.1

Update to OpenSSL 1.1.1d for Ruby 2.5+

---

share/ruby-build/2.7.0-rc2

https://www.ruby-lang.org/en/news/2019/12/21/2-7-0-rc2-released/

add ruby 2.7.0-rc2

---

script/update-truffleruby
share/ruby-build/truffleruby-1.0.0-rc10
share/ruby-build/truffleruby-1.0.0-rc11
share/ruby-build/truffleruby-1.0.0-rc12
share/ruby-build/truffleruby-1.0.0-rc13
share/ruby-build/truffleruby-1.0.0-rc14
share/ruby-build/truffleruby-1.0.0-rc15
share/ruby-build/truffleruby-1.0.0-rc16
share/ruby-build/truffleruby-1.0.0-rc2
share/ruby-build/truffleruby-1.0.0-rc3
share/ruby-build/truffleruby-1.0.0-rc5
share/ruby-build/truffleruby-1.0.0-rc6
share/ruby-build/truffleruby-1.0.0-rc7
share/ruby-build/truffleruby-1.0.0-rc8
share/ruby-build/truffleruby-1.0.0-rc9
share/ruby-build/truffleruby-19.0.0
share/ruby-build/truffleruby-19.1.0
share/ruby-build/truffleruby-19.2.0
share/ruby-build/truffleruby-19.2.0.1
share/ruby-build/truffleruby-19.3.0

Fixes a minor issue in error messages of https://github.com/rbenv/ruby-build/pull/1383

Fix error message for unrecognized operating system

---

share/ruby-build/truffleruby-19.3.0.2

I noticed that there is new version for truffleruby and created a file for installing it.

Create definition file truffleruby-19.3.0.2

---

bin/ruby-build
share/ruby-build/artichoke-dev

💎 Artichoke is an alternative Ruby implementation made in Rust 🚀 
This allows to install the latest Artichoke nightly build from the official repository https://github.com/artichoke/nightly/releases
/cc @lopopolo

Add artichoke-dev to install the latest Artichoke nightly build

---

share/ruby-build/jruby-9.2.12.0

Add definition for JRuby 9.2.12.0
https://www.jruby.org/2020/07/01/jruby-9-2-12-0.html

Add definition for JRuby 9.2.12.0

---

share/ruby-build/mruby-2.1.2

https://github.com/mruby/mruby/releases/tag/2.1.2

Add definition for mruby 2.1.2

---

bin/rbenv-install

As far as I search on Twitter, the short option is not well known.

[easy] promote 'rbenv install -L', an alias of '--list-all'

---

share/ruby-build/3.1.0-dev

Development of 3.1.0 started.
https://github.com/ruby/ruby/commit/c591ab11ce3b74a364c4c4b2003626033daf0757

Add definition for Ruby 3.1.0-dev

---

share/ruby-build/jruby-9.2.16.0

https://www.jruby.org/2021/03/03/jruby-9-2-16-0.html

Add definition for JRuby 9.2.16.0

---

share/ruby-build/mruby-3.0.0

Added mruby-3.0.0

---

.github/workflows/ci.yml
.travis.yml
script/test
script/travis
test/test_helper.bash

Run Linux CI and script/mirror verify in GitHub Actions

---

share/ruby-build/truffleruby+graalvm-dev

Using the builds from https://github.com/graalvm/graalvm-ce-dev-builds/releases/latest

Add truffleruby+graalvm-dev

---

script/update-jruby
share/ruby-build/jruby-9.3.0.0

Fixes https://github.com/rbenv/ruby-build/issues/1796

Add JRuby 9.3.0.0

---

share/ruby-build/2.6.9
share/ruby-build/2.7.5
share/ruby-build/3.0.3

- https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-6-9-released/
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-7-5-released/
- https://www.ruby-lang.org/en/news/2021/11/24/ruby-3-0-3-released/

Add ruby 2.6.9, 2.7.5 and 3.0.3

---

share/ruby-build/2.6.10
share/ruby-build/2.7.6
share/ruby-build/3.0.4
share/ruby-build/3.1.2

- https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-0-4-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-6-10-released/
cc @hsbt @eregon

Add Ruby 3.1.2, 3.0.4, 2.7.6, 2.6.10

---

bin/ruby-build

Reported by https://twitter.com/tagomoris/status/1568467163740250113 (ja)

bash didn't provide \d

---

README.md

Part of https://github.com/rbenv/rbenv/pull/1433

Touch up README for comprehension and clarity

---

bin/rbenv-install
test/rbenv.bats

Followup to https://github.com/rbenv/ruby-build/pull/2055
Fixes https://github.com/rbenv/ruby-build/issues/2058

Fix `rbenv install --list` exit status

---

bin/ruby-build

* No definition uses it anymore.

Remove patch for openssl-1.1.1q

---

share/ruby-build/jruby-1.5.6
share/ruby-build/jruby-1.6.3
share/ruby-build/jruby-1.6.4
share/ruby-build/jruby-1.6.5
share/ruby-build/jruby-1.6.5.1
share/ruby-build/jruby-1.6.6
share/ruby-build/jruby-1.6.7
share/ruby-build/jruby-1.6.7.2
share/ruby-build/jruby-1.6.8
share/ruby-build/jruby-1.7.0
share/ruby-build/jruby-1.7.0-preview1
share/ruby-build/jruby-1.7.0-preview2
share/ruby-build/jruby-1.7.0-rc1
share/ruby-build/jruby-1.7.0-rc2
share/ruby-build/jruby-1.7.1
share/ruby-build/jruby-1.7.10
share/ruby-build/jruby-1.7.11
share/ruby-build/jruby-1.7.12
share/ruby-build/jruby-1.7.13
share/ruby-build/jruby-1.7.14
share/ruby-build/jruby-1.7.15
share/ruby-build/jruby-1.7.16
share/ruby-build/jruby-1.7.2
share/ruby-build/jruby-1.7.3
share/ruby-build/jruby-1.7.4
share/ruby-build/jruby-1.7.5
share/ruby-build/jruby-1.7.6
share/ruby-build/jruby-1.7.7
share/ruby-build/jruby-1.7.8
share/ruby-build/jruby-1.7.9

https://github.com/rbenv/ruby-build/pull/2140#issuecomment-1421513364

Update old versions of JRuby URLs

---

.github/workflows/differential-shellcheck.yml

https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/215

Avoid shellcheck CI job commenting on every PR

---

.github/workflows/differential-shellcheck.yml

Followup to https://github.com/rbenv/ruby-build/pull/2176

Fix uploading SARIF reports from Differential Shellcheck

---

share/ruby-build/truffleruby+graalvm-dev

Update URLs for truffleruby+graalvm-dev

---

share/ruby-build/3.1.0
share/ruby-build/3.1.0-dev
share/ruby-build/3.1.0-preview1
share/ruby-build/3.1.1
share/ruby-build/3.1.2
share/ruby-build/3.1.3
share/ruby-build/3.1.4
share/ruby-build/3.2.0
share/ruby-build/3.2.0-dev
share/ruby-build/3.2.0-preview1
share/ruby-build/3.2.0-preview2
share/ruby-build/3.2.0-preview3
share/ruby-build/3.2.0-rc1
share/ruby-build/3.2.1
share/ruby-build/3.2.2
share/ruby-build/3.3.0-dev
share/ruby-build/3.3.0-preview1
share/ruby-build/3.3.0-preview2

https://www.openssl.org/news/secadv/20231024.txt

Bump up OpenSSL 3.1.4

---

.gitattributes
Makefile
bin/rbenv-install
bin/ruby-build
install.sh
script/release
share/man/man1/ruby-build.1
share/man/man1/ruby-build.1.adoc
test/installer.bats
test/rbenv.bats

Add ruby-build(1) man page

---

share/ruby-build/3.3.0-preview3

Added the [preview3 for 3.3.0](https://www.ruby-lang.org/en/news/2023/11/12/ruby-3-3-0-preview3-released/).

Added 3.3.0-preview3

---

.github/workflows/ci.yml

ref. https://github.com/rbenv/rbenv/pull/1544

Use bats-core instead of archived version

---

share/ruby-build/3.1.0
share/ruby-build/3.1.0-dev
share/ruby-build/3.1.0-preview1
share/ruby-build/3.1.1
share/ruby-build/3.1.2
share/ruby-build/3.1.3
share/ruby-build/3.1.4
share/ruby-build/3.1.5
share/ruby-build/3.2.0
share/ruby-build/3.2.0-dev
share/ruby-build/3.2.0-preview1
share/ruby-build/3.2.0-preview2
share/ruby-build/3.2.0-preview3
share/ruby-build/3.2.0-rc1
share/ruby-build/3.2.1
share/ruby-build/3.2.2
share/ruby-build/3.2.3
share/ruby-build/3.2.4
share/ruby-build/3.3.0
share/ruby-build/3.3.0-dev
share/ruby-build/3.3.0-preview1
share/ruby-build/3.3.0-preview2
share/ruby-build/3.3.0-preview3
share/ruby-build/3.3.0-rc1
share/ruby-build/3.3.1
share/ruby-build/3.4-dev
share/ruby-build/ruby-dev

Ref. https://github.com/rbenv/ruby-build/pull/2370#issuecomment-2077076689

Upgrade to OpenSSL 3.1.5

---

share/ruby-build/3.3.3
share/ruby-build/3.3.4

Fixed at https://github.com/rbenv/ruby-build/pull/2421#issuecomment-2216334698

Use LTS version of OpenSSL 3

---

share/ruby-build/1.8.7-p375
share/ruby-build/1.9.2-p326

Fixed https://github.com/rbenv/ruby-build/issues/2478

Removed unofficial releases
