share/ruby-build/jruby-9000+graal-dev, share/ruby-build/jruby-9000-dev
jruby-9000-* is obsoleted names. it should be removed.
=> removed jruby-9000 definitions

share/ruby-build/2.0.0-p645, share/ruby-build/2.1.6, share/ruby-build/2.2.2
Updated the checksums in PR #738 which was done a few hours ago but went unnoticed. 
This really is rather important folks, lots of people rely on ruby-build for their versions and today is panic security update day, so it would be great to merge this.
=> Add 2.2.2, 2.1.6 and 2.0.0-p645 but they work

bin/rbenv-install, test/rbenv.bats
When a target is not found, rbenv-install proposes pulling changes from
upstream. This involves changing the directory to the ruby-build checkout.
This patch adds a '&& cd -' to change the working directory back to where
we've been. Should work on at least Bash and Zsh.
=> Add 'cd -' to proposed steps to upgrade ruby-build

bin/ruby-build
We can specify inet protocol via command line option.
I don't want to change system settings persistently.
Such as editing /etc/sysctl.conf.
=> Specify inet protocol

share/ruby-build/rbx-2.5.3
This PR adds rbx-2.5.3 (rubinius) to available version list, supported by ruby-build.
Release note: https://github.com/rubinius/rubinius/releases/tag/v2.5.3
Thank you for ruby-build. It's really useful and convenient.
=> add rbx-2.5.3

bin/ruby-build, test/build.bats
OpenJDK reports its version slightly different than Oracle Java, and
this was causing the logic in bin/ruby-build to not detect Java 7 or
higher when OpenJDK was used.
=> Properly detect OpenJDK versions in bin/ruby-build

README.md
See https://37signals.com/ for announcement post.
=> 37signals renamed themselves to Basecamp, so update sponsor in README

bin/rbenv-install, bin/rbenv-uninstall, test/rbenv.bats
The sed fallback was necessary before rbenv 0.4.0, which has been out for 2.5 years. I think it's time we can remove the fallback and just rely on rbenv-help.
=> remove sed fallback for help/usage

bin/ruby-build
This lists through all installed Homebrew packages named "llvm\*" and tests each `llvm-config --version` for "3.5\*" until it finds one.
Alternative to #764
/cc @brandt
=> Improve detecting LLVM 3.5 from Homebrew

bin/ruby-build
Before, we detected whether `require "openssl"` works after compiling Ruby 2.0.0+ and failed the build if the openssl extension never compiled. This change extends this practice to zlib, yaml and readline as well since we consider these to be essential packages for most Ruby development. Rubygems won't work, for instance, without zlib.
This also suggests how you could install necessary dependencies if a package manager `apt-get` or `yum` is detected on the system.
Example output:
The Ruby zlib extension was not compiled.
The Ruby openssl extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Try running `apt-get install -y libssl-dev zlib1g-dev` to fetch missing dependencies
Pros:
- Detects stuff like #509 or #557 and aborts the install
- Tells you how you can …
=> Check that openssl, yaml, readline, zlib are all loadable

share/ruby-build/1.8.6-p383, share/ruby-build/1.8.6-p420, share/ruby-build/1.8.7-p249, share/ruby-build/1.8.7-p302, share/ruby-build/1.8.7-p334, share/ruby-build/1.8.7-p352, share/ruby-build/1.8.7-p357, share/ruby-build/1.8.7-p358, share/ruby-build/1.8.7-p370, share/ruby-build/1.8.7-p371, share/ruby-build/1.8.7-p374, share/ruby-build/1.8.7-p375, share/ruby-build/1.9.1-p378, share/ruby-build/1.9.1-p430, share/ruby-build/1.9.2-p0, share/ruby-build/1.9.2-p180, share/ruby-build/1.9.2-p290, share/ruby-build/1.9.2-p318, share/ruby-build/1.9.2-p320, share/ruby-build/1.9.2-p326, share/ruby-build/1.9.2-p330, share/ruby-build/1.9.3-p0, share/ruby-build/1.9.3-p125, share/ruby-build/1.9.3-preview1, share/ruby-build/rbx-1.2.4, share/ruby-build/ree-1.8.7-2011.03, share/ruby-build/ree-1.8.7-2011.12, share/ruby-build/ree-1.8.7-2012.01
Swap from directly using CDN to https://rubygems.org, which just redirects to CDN (but then allows for easy change of CDN in future).
=> Rubygems added a redirect on their main domain, so use it as the canonical download URL

share/ruby-build/rbx-1.2.4, share/ruby-build/rbx-2.0.0, share/ruby-build/rbx-2.1.0, share/ruby-build/rbx-2.1.1, share/ruby-build/rbx-2.2.0, share/ruby-build/rbx-2.2.1, share/ruby-build/rbx-2.2.10, share/ruby-build/rbx-2.2.2, share/ruby-build/rbx-2.2.3, share/ruby-build/rbx-2.2.4, share/ruby-build/rbx-2.2.5, share/ruby-build/rbx-2.2.6, share/ruby-build/rbx-2.2.7, share/ruby-build/rbx-2.2.9, share/ruby-build/rbx-2.3.0, share/ruby-build/rbx-2.4.0, share/ruby-build/rbx-2.4.1, share/ruby-build/rbx-2.5.0, share/ruby-build/rbx-2.5.1, share/ruby-build/rbx-2.5.2, share/ruby-build/rbx-2.5.3, share/ruby-build/rbx-2.5.4, share/ruby-build/rbx-2.5.5, share/ruby-build/rbx-2.5.6, share/ruby-build/rbx-2.5.7, share/ruby-build/rbx-2.5.8
The Rubinius folk updated their download links to use https://, so let's match that now.
=> Update Rubinius download location to use https://

share/ruby-build/2.0.0-p647, share/ruby-build/2.1.7, share/ruby-build/2.2.3
We released stable and old stable version of ruby.
* https://www.ruby-lang.org/en/news/2015/08/18/ruby-2-0-0-p647-released/
* https://www.ruby-lang.org/en/news/2015/08/18/ruby-2-1-7-released/
* https://www.ruby-lang.org/en/news/2015/08/18/ruby-2-2-3-released/
=> Ruby 2.2.3, Ruby 2.1.7 and Ruby 2.0.0-p647

share/ruby-build/jruby-9.0.2.0+graal-dev, share/ruby-build/jruby-master+graal-dev
the old JRuby 9.0.0.0+graal-dev installs outdated version
=> Add JRuby 9.0.2.0+graal-dev

share/ruby-build/1.9.3-dev, share/ruby-build/1.9.3-p0, share/ruby-build/1.9.3-p125, share/ruby-build/1.9.3-p194, share/ruby-build/1.9.3-p286, share/ruby-build/1.9.3-p327, share/ruby-build/1.9.3-p362, share/ruby-build/1.9.3-p374, share/ruby-build/1.9.3-p385, share/ruby-build/1.9.3-p392, share/ruby-build/1.9.3-p429, share/ruby-build/1.9.3-p448, share/ruby-build/1.9.3-p484, share/ruby-build/1.9.3-p545, share/ruby-build/1.9.3-p547, share/ruby-build/1.9.3-p550, share/ruby-build/1.9.3-p551, share/ruby-build/1.9.3-preview1, share/ruby-build/1.9.3-rc1
OpenSSL is not compiled into Ruby 1.9.3 when installing on OS X 10.11 El Capitan.
To resolve this issue let's install the OpenSSL package when `has_broken_mac_openssl`.
=> install OpenSSL for 1.9.3

README.md
LICENSE already exists as its own file (https://github.com/sstephenson/ruby-build/blob/master/LICENSE)
=> Remove license from readme

script/test
According to https://github.com/travis-ci/travis-ci/issues/1719 (closed by https://github.com/travis-ci/travis-core/pull/383), the behavior of $TRAVIS_COMMIT_RANGE should be correct now. We should be able to use it directly.
=> TRAVIS_COMMIT_RANGE is correct now

test/test_helper.bash
Ensure that if `TMP` is empty, we don't do bad things, like `rm -rf /*`
=> safer teardown

share/ruby-build/2.3.0-dev, share/ruby-build/2.4.0-dev
We branched stable version of ruby 2.3.0 today. I switched it in `2.3.0-dev` definition.
and added 2.4.0-dev definition. It version still uses `2.3.0`. but matz will bump version `2.4.0` at few days later :octocat:
=> Ruby 2.3.0 branch and trunk

share/ruby-build/2.3.0
https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/
=> added definition of Ruby 2.3.0

bin/ruby-build, share/ruby-build/rbx-2.5.8, share/ruby-build/rbx-2.6.0, share/ruby-build/rbx-2.7.0, share/ruby-build/rbx-2.8.0, share/ruby-build/rbx-2.9.0
Also, support Rubinius linking against Homebrew openssl due to OS X not shipping with system OpenSSL headers anymore.
=> Add rbx-2.6.0, rbx-2.7.0, rbx-2.8.0, rbx-2.9.0

bin/ruby-build
When installing on a system without bzip2, build would fail with little help. Added a message to the log file that states bzip2 is missing from path, and when build fails, try installing bzip2.
#870 has further details
=> add message when bzip2 is missing and package type is bz2

share/ruby-build/rbx-3.0.0
I'm aware of issue #862 but in the meantime, hoping it will get resolved w/o removing rubinius support, here is the file for rbx-3.0.0 — a simple copy from 2.11.0 w/ SHA and filenames edited. It builds and installs fine.
Thanks.
=> Add metadata for Rubinius 3.0 aka rbx-3.0.0.

share/ruby-build/rbx-2.10.0, share/ruby-build/rbx-2.11.0, share/ruby-build/rbx-2.6.0, share/ruby-build/rbx-2.7.0, share/ruby-build/rbx-2.8.0, share/ruby-build/rbx-2.9.0
Updated via the [rubinius scraper](https://github.com/jasonkarns/ruby-build-update-defs/pull/2)!!!
=> Update rubinius builds openssl from 1.0.1q to 1.0.2e

bin/rbenv-install, bin/ruby-build, test/rbenv.bats
- Add missing `-4` and `-6` flags to ruby-build usage
- Add missing `--version` flag to ruby-build and rbenv-install usage
- Order flags alphabetically
- Add missing `-s` flag to rbenv-install usage
How should rbenv-install usage show that `-f` and `-s` are mutually exclusive? (Or rather that `-s` actually takes precedence?) Related, should the code be changed to error out (with usage help) when both `-f` and `-s` are present?
=> Clean up usage documentation

bin/rbenv-install, bin/rbenv-uninstall
Handled by rbenv itself: https://github.com/rbenv/rbenv/blob/3997a394d975136f468be196941492d3d0ef5143/libexec/rbenv#L53-L58
Extracted from #880
=> rbenv ensures RBENV_ROOT is set for us

bin/ruby-build, test/cache.bats, test/checksum.bats, test/fixtures/definitions/with-invalid-checksum
Per the discussion from #881, this PR is the refactor of checksum handling.
- `has_checksum_support` function tests for support of the provided checksum algorithm, memoizing results
- `verify_checksum` now picks the algorithm based on checksum length. unexpected lengths no longer default to sha1(256bit), but rather error out. (They would error out eventually, anyway, when the resulting checksum doesn't match.)
- `HAS_X_SUPPORT` variables are no longer necessary
- algorithm support is now checked lazily; it is no longer checked if it wouldn't be used
=> Checksum refactor

test/build.bats, test/cache.bats, test/checksum.bats, test/definitions.bats, test/hooks.bats, test/mirror.bats, test/rbenv.bats, test/test_helper.bash
The current test suite uses the `assert` inconsistently. In some cases, `assert` is used. In others, the bash test built-in is used (or other 'naked' command).
The assert helper provides a marginal improvement in the error output when it fails, but this is minimal. Rather, I think the assert (and refute) test helpers improve the clarity of the test itself in signifiying the purpose of the commands. It helps clarify the arrange/act/assert sub-sections of each test.
=> Leverage assertion test helpers

share/ruby-build/rbx-1.2.4, share/ruby-build/rbx-2.0.0, share/ruby-build/rbx-2.0.0-dev, share/ruby-build/rbx-2.0.0-rc1, share/ruby-build/rbx-2.1.0, share/ruby-build/rbx-2.1.1, share/ruby-build/rbx-2.2.0, share/ruby-build/rbx-2.2.1, share/ruby-build/rbx-2.2.10, share/ruby-build/rbx-2.2.2, share/ruby-build/rbx-2.2.3, share/ruby-build/rbx-2.2.4, share/ruby-build/rbx-2.2.5, share/ruby-build/rbx-2.2.6, share/ruby-build/rbx-2.2.7, share/ruby-build/rbx-2.2.8, share/ruby-build/rbx-2.2.9, share/ruby-build/rbx-2.3.0, share/ruby-build/rbx-2.4.0, share/ruby-build/rbx-2.4.1, share/ruby-build/rbx-2.5.0, share/ruby-build/rbx-2.5.1, share/ruby-build/rbx-2.5.2, share/ruby-build/rbx-2.5.3, share/ruby-build/rbx-2.5.4, share/ruby-build/rbx-2.5.5, share/ruby-build/rbx-2.5.6, share/ruby-build/rbx-2.5.7, share/ruby-build/rbx-2.5.8
I found new urls for old Rubinius binaries on the Github. It seems the latest binary is for 2.2.2 (in ruby-build). See https://github.com/rubinius/rubinius/releases?after=v2.2.2. The rest is probably gone and nowhere publicly. So there is a question if Rubinius 2.2.1 and later should be removed.
=> New urls for old Rubinius versions and unavailable versions removed

bin/ruby-build, share/ruby-build/jruby-9.0.0.0+graal-dev, share/ruby-build/jruby-9.0.2.0+graal-dev, share/ruby-build/jruby-master+graal-dev, test/build.bats
Thanks very much for accepting our definition files for JRuby that bundled Graal (our new JIT compiler for Java). This was really useful when there was no other way to get Graal, but now there are official experimental releases available from Oracle https://github.com/jruby/jruby/wiki/Downloading-GraalVM and soon it will be possible to just use an early access of Java 9 https://github.com/jruby/jruby/wiki/Using-Graal-in-JDK-9-EA-Builds, so these bundled versions aren't necessary any more and we can remove them.
=> Remove builds of JRuby that bundle Graal

share/ruby-build/2.1.9
This adds the definition for Ruby 2.1.9 based on the definition of 2.1.8 (also uses `openssl-1.0.2g`).
https://www.ruby-lang.org/en/news/2016/03/30/ruby-2-1-9-released/
=> Added definition of Ruby 2.1.9

bin/ruby-build, test/build.bats, test/cache.bats, test/checksum.bats, test/fetch.bats, test/mirror.bats
[aria2](https://aria2.github.io/) is the "ultra fast" downloader and it supports parallel download with Range header, resuming failed download attempts, and so on. I received a feature request for this as yyuu/pyenv#534 from @luzfcb who is living in Brazil. I think this feature could be useful for all users who suffered by unstable internet connection.
=> Use `aria2c` the "ultra fast" downloader if available

share/ruby-build/2.4.0-preview1
:octocat: https://www.ruby-lang.org/en/news/2016/06/20/ruby-2-4-0-preview1-released/
=> Added 2.4.0prewview1 definitions

bin/ruby-build, test/build.bats, test/cache.bats, test/checksum.bats, test/fetch.bats, test/hooks.bats, test/mirror.bats, test/rbenv.bats, test/test_helper.bash
I've implemented `aria2c` support in #904. However, I finally realized that `aria2c` doesn't support writing remote content to stdout (https://github.com/aria2/aria2/issues/190).
I confirmed that basically this must be not a problem for ruby-build since it doesn't rely on `http get` without filename ([the only usage of http get](https://github.com/rbenv/ruby-build/blob/3304f96296c9912eaee27347e87e93a3e8fc5a29/bin/ruby-build#L412) is specifying its destination filename). It'd be better to be fixed though.
=> `aria2c` doesn't support writing remote content to stdout

bin/ruby-build, test/checksum.bats, test/hooks.bats, test/mirror.bats, test/rbenv.bats, test/test_helper.bash
Bats doesn't support both suite-wide setup (in helper) *and* file-wide
setup. Which means the existance of any file-level setup() function
overwrites any setup() function from test_helper. This can be confusing,
and (IMO) easier to simply avoid the overwriting and remove any
_implied_ suite-wide setup function from test_helper.
This turns out to not be so bad for the recently added setup function,
because the only test files that actually need aria2c removed from PATH
are those that actually invoke curl. These can be found because they are
the only test files that stub curl; half of which already had
file-specific setup() functions. So the only ones which need a
file-local setup() function added were: checksum.bats and mirror.bats
Along these lines, rbenv.bats and hooks.bats were removing …
=> Remove suite-wide setup

share/ruby-build/2.4.0-preview2
https://www.ruby-lang.org/en/news/2016/09/08/ruby-2-4-0-preview2-released/
=> add 2.4.0-prewview2 definitions

README.md
I stumbled several times over the update behavior for HEAD packages in brew so I thought, the hint might be useful to other users, too.
=> Clarify reinstalling behavior for HEAD package

bin/ruby-build, share/ruby-build/rbx-3.30, share/ruby-build/rbx-3.31, share/ruby-build/rbx-3.32, share/ruby-build/rbx-3.33, share/ruby-build/rbx-3.34, share/ruby-build/rbx-3.35, share/ruby-build/rbx-3.36, share/ruby-build/rbx-3.37, share/ruby-build/rbx-3.38, share/ruby-build/rbx-3.39, share/ruby-build/rbx-3.40, share/ruby-build/rbx-3.41, share/ruby-build/rbx-3.42, share/ruby-build/rbx-3.43, share/ruby-build/rbx-3.44, share/ruby-build/rbx-3.45, share/ruby-build/rbx-3.46, share/ruby-build/rbx-3.47, share/ruby-build/rbx-3.48
From 3.30 onwards, Rubinius requires LLVM 3.6 or newer: https://github.com/rubinius/rubinius/commit/2dd51a1c285d1adae7224d4c966f664a11ed447e
Previously discussed here: https://github.com/rbenv/ruby-build/pull/765#issuecomment-105488542
=> Require LLVM 3.6 when building Rubinius 3.30+

share/ruby-build/2.4.0-preview3
https://www.ruby-lang.org/en/news/2016/11/09/ruby-2-4-0-preview3-released/
=> added definition for 2.4.0-preview3

share/ruby-build/2.2.6, share/ruby-build/2.3.2
* https://www.ruby-lang.org/ja/news/2016/11/15/ruby-2-2-6-released/
* https://www.ruby-lang.org/ja/news/2016/11/15/ruby-2-3-2-released/
=> Added 2.2.6 and 2.3.2 definitions

share/ruby-build/2.3.3
https://www.ruby-lang.org/en/news/2016/11/21/ruby-2-3-3-released/
=> Added definition of Ruby 2.3.3

bin/ruby-build, test/build.bats, test/compiler.bats
ruby-build fails when I use on FreeBSD 11-RELEASE.
```
$ rbenv install 2.3.1
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...
BUILD FAILED (FreeBSD 11.0-RELEASE-p2 using ruby-build 20160913-13-g8ef0c34)
Inspect or clean up the working tree at /tmp/ruby-build.20161104153337.41276
Results logged to /tmp/ruby-build.20161104153337.41276.log
Last 10 log lines:
rake 10.4.2
installing rdoc:              /home/yuichiro/.rbenv/versions/2.3.1/share/ri/2.3.0/system
installing capi-docs:         /home/yuichiro/.rbenv/versions/2.3.1/share/doc/ruby
The Ruby readline extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
--prefix=/home/yuichiro-n/.rbenv/versions/2.3.1
CFLAGS= -O3 …
```
=> support FreeBSD 11-RELEASE

README.md
From `brew upgrade --help`:
>     If --fetch-HEAD is passed, fetch the upstream repository to detect if
>     the HEAD installation of the formula is outdated. Otherwise, the
>     repository's HEAD will be checked for updates when a new stable or devel
>     version has been released.
=> Homebrew upgrade for HEAD package.

bin/ruby-build
When a user uses homebrew packages (e.g. openssl), then to upgrade them the user must update homebrew packages before rebuilding using ruby-build.
=> print when using homebrew packages

share/ruby-build/rbx-3.61, share/ruby-build/rbx-3.62, share/ruby-build/rbx-3.63, share/ruby-build/rbx-3.64, share/ruby-build/rbx-3.65, share/ruby-build/rbx-3.66, share/ruby-build/rbx-3.67, share/ruby-build/rbx-3.68, share/ruby-build/rbx-3.69
In the other definitions — for example —
```
install_package "rubinius-3.60" "https://rubinius-releases-rubinius-com.s3.amazonaws.com/rubinius-3.60.tar.bz2#39f83fc74216391af56ea1ad13372878c0ed41fae49ee6a8cf8b0369a54c3b57" rbx
```
is `39f83fc74216391af56ea1ad13372878c0ed41fae49ee6a8cf8b0369a54c3b57` the checksum?
How do I find or generate that?
=> Added definitions for Rubinius 3.61–3.69

share/ruby-build/2.4.0, share/ruby-build/2.4.0-dev, share/ruby-build/2.5.0-dev
This is just proposal to use OpenSSL for Ruby 2.4 and later versions.
If I remember correctly, OpenSSL 1.1.0 is only supported since Ruby 2.4 (https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/) and it's unsupported in Ruby 2.3 and in earlier versions (@hsbt could you please to confirm it)?
=> [Proposal] Use OpenSSL 1.1.0 for Ruby 2.4+

bin/ruby-build, test/compiler.bats
I fixed a problem about gcc is installed on FreeBSD-11.
The problem is simple.
When I install gcc on my FreeBSD,
ruby-build fails to compile for all ruby versions.
ruby-build adds "-Wno-error=shorten-64-to-32" option to CFLAGS,
when cc is clang. (clang is the default compiler of FreeBSD-11)
But if the configure script of ruby detects gcc,
ruby is compiled with "gcc -Wno-error=shorten-64-to-32",
it will fail because gcc doesn't supports "-Wno-error=shorten-64-to-32" option.
My patch checks if gcc is not installed,
and then adds "-Wno-error=shorten-64-to-32" option to CFLAGS.
Will you merge this Pull Request?
=> gcc is installed on FreeBSD

bin/ruby-build, test/definitions.bats
It should be:
```
1.8.7
1.8.7-p72
1.8.7-p374
1.8.7-p375
```
It was:
```
1.8.7-p374
1.8.7-p375
1.8.7-p72
1.8.7
```
=> fix ordering for versions with different length patch number

bin/ruby-build
Hi,
it seems to me that `RUBY_BUILD_VERSION` should be bumped according to recent release, shouldn't it?
=> ruby-build 20170322

share/ruby-build/jruby-9.1.9.0-dev
This pull request adds JRuby 9.1.9.0 snapshot installation.
```
$ rbenv install jruby-9.1.9.0-dev
Downloading jruby-bin-9.1.9.0-SNAPSHOT.tar.gz...
-> http://ci.jruby.org/snapshots/master/jruby-bin-9.1.9.0-SNAPSHOT.tar.gz
Installing jruby-9.1.9.0-SNAPSHOT...
Installed jruby-9.1.9.0-SNAPSHOT to /home/yahonda/.rbenv/versions/jruby-9.1.9.0-dev
$ ruby -v
jruby 9.1.9.0-SNAPSHOT (2.3.3) 2017-04-03 e7bcde5 OpenJDK 64-Bit Server VM 25.121-b14 on 1.8.0_121-b14 +jit [linux-x86_64]
```
=> Add JRuby 9.1.9.0 snapshot

share/ruby-build/jruby-1.7.27
JRuby added one more version in the 1.7 series.  This adds the ability to install that.
=> Add JRuby 1.7.27

bin/ruby-build
macOS 10.13 High Sierra has replaced OpenSSL 0.9.8 with LibreSSL 2.2.7. Even though, the header files (`ssl.h` etc.) aren't included, so we can't use this to build Ruby.
This pull request changes `has_broken_mac_openssl()` to ignore LibreSSL bundled with macOS 10.13.
=> Ignore LibreSSL bundled with macOS 10.13

share/ruby-build/2.1.0, share/ruby-build/2.1.0-dev, share/ruby-build/2.1.0-preview1, share/ruby-build/2.1.0-preview2, share/ruby-build/2.1.0-rc1, share/ruby-build/2.1.1, share/ruby-build/2.1.10, share/ruby-build/2.1.2, share/ruby-build/2.1.3, share/ruby-build/2.1.4, share/ruby-build/2.1.5, share/ruby-build/2.1.6, share/ruby-build/2.1.7, share/ruby-build/2.1.8, share/ruby-build/2.1.9
=> Ruby 2.1 reached end of life on 2017-03-31

share/ruby-build/2.2.0, share/ruby-build/2.2.0-dev, share/ruby-build/2.2.0-preview1, share/ruby-build/2.2.0-preview2, share/ruby-build/2.2.0-rc1, share/ruby-build/2.2.1, share/ruby-build/2.2.2, share/ruby-build/2.2.3, share/ruby-build/2.2.4, share/ruby-build/2.2.5, share/ruby-build/2.2.6, share/ruby-build/2.2.7
=> Ruby 2.2 entered unsupported security maintenance on 2016-12-25

bin/ruby-build, share/ruby-build/2.2.0-dev, share/ruby-build/2.3.0-dev, share/ruby-build/2.4.0-dev, share/ruby-build/2.5.0-dev
Fixes #1093 
Added `make update-gems` command before `make install` when installing to 2.5.0-dev named "ruby-trunk"
/cc @k0kubun
I'm not a familiar with shell script. Can I handle ruby-trunk, ruby-2.4.0-dev and ruby-2.3.0-dev smartly?
=> invoke make update-gems before make install with ruby-trunk

bin/ruby-build
- Only call `openssl version` once;
- Make the check work with future version of LibreSSL after 2.2.7. This assumes that Apple might keep updating LibreSSL shipping with macOS, but that they will never provide header files.
Followup to https://github.com/rbenv/ruby-build/pull/1095
/cc @hsbt @osyoyu
=> Improve check for openssl on macOS

share/ruby-build/jruby-9.2.0.0-dev
```ruby
$ rbenv install jruby-9.2.0.0-dev
Downloading jruby-bin-9.2.0.0-SNAPSHOT.tar.gz...
-> http://ci.jruby.org/snapshots/master/jruby-bin-9.2.0.0-SNAPSHOT.tar.gz
Installing jruby-9.2.0.0-SNAPSHOT...
/home/yahonda/.rbenv/plugins/ruby-build/bin/ruby-build: line 717: warning: command substitution: ignored null byte in input
/home/yahonda/.rbenv/plugins/ruby-build/bin/ruby-build: line 717: warning: command substitution: ignored null byte in input
Installed jruby-9.2.0.0-SNAPSHOT to /home/yahonda/.rbenv/versions/jruby-9.2.0.0-dev
$ rbenv global jruby-9.2.0.0-dev
$ ruby -v
jruby 9.2.0.0-SNAPSHOT (2.4.1) 2017-08-15 ef6da47 OpenJDK 64-Bit Server VM 25.141-b16 on 1.8.0_141-b16 +jit [linux-x86_64]
```
=> Add JRuby 9.2.0.0 snapshot

share/ruby-build/jruby-9.1.13.0
This pull request enables to install JRuby 9.1.13.0
http://jruby.org/2017/09/06/jruby-9-1-13-0
```ruby
$ rbenv install jruby-9.1.13.0
Downloading jruby-bin-9.1.13.0.tar.gz...
-> https://s3.amazonaws.com/jruby.org/downloads/9.1.13.0/jruby-bin-9.1.13.0.tar.gz
Installing jruby-9.1.13.0...
/home/yahonda/.rbenv/plugins/ruby-build/bin/ruby-build: line 717: warning: command substitution: ignored null byte in input
/home/yahonda/.rbenv/plugins/ruby-build/bin/ruby-build: line 717: warning: command substitution: ignored null byte in input
Installed jruby-9.1.13.0 to /home/yahonda/.rbenv/versions/jruby-9.1.13.0
$ rbenv global jruby-9.1.13.0
$ ruby -v
jruby 9.1.13.0 (2.3.3) 2017-09-06 8e1c115 OpenJDK 64-Bit Server VM 25.141-b16 on 1.8.0_141-b16 +jit [linux-x86_64]
$
```
=> Add JRuby 9.1.13.0

bin/ruby-build
The issue has originarily reported as pyenv/pyenv#902.
Unlike sha256sum of GNU coreutils, BusyBox one doesn't print '*' and prints extra whitespaces, when computing digest from stdin.
sha256sum (GNU coreutils 8.26)
```
% cat /sbin/init | sha256sum -b
ef753e9504ada221155b86e7e6b7b4ff2499d64e27bcd959f0542bcac589feb1 *-
```
sha256sum (BusyBox v1.26.2)
```
/ # cat /sbin/init | sha256sum -b
4cd6d1a4028772fabc9166bb52b5826aec4e91874c107fce33dc515c04cb754f  -
```
I also confirmed that md5sum behaves just similarly.
Actually sha256sum feature won't work correctly even with this unless merging #1059.
=> Ignore everything after whitespace in the output from sha256sum

bin/ruby-build
Currently, if you pass an argument like '-v' or '-k' to ruby-build on a FreeBSD system, you get a shell syntax warning about '=' being used as a unary operator.
This is happening because of some missing quotes, and no longer complains once they are added.
=> Quote JRuby check on FreeBSD to avoid "unary operator" syntax issue.

bin/ruby-build
The option is available only if verifying digest, not available when computing digest.
>       --quiet
>              don't print OK for each successfully verified file
=> `--quiet` option isn't sensible sha256sum(1) of GNU coreutils

share/ruby-build/2.5.0-preview1
https://www.ruby-lang.org/en/news/2017/10/10/ruby-2-5-0-preview1-released/
=> Added 2.5.0-preview1 definition

share/ruby-build/jruby-9.1.14.0
JRuby 9.1.14.0 has been released.
http://jruby.org/2017/11/08/jruby-9-1-14-0.html
JRuby 9.1.14.0+ download URL has changed.
https://github.com/rbenv/ruby-build/issues/1148
=> Add definition for JRuby 9.1.14.0

bin/ruby-build, test/build.bats
This allows the java version to be specified as "9", instead of "1.9".
Closes #1135
=> Relax java version regexp

share/ruby-build/jruby-9.1.15.0
This pull request adds JRuby 9.1.15.0
http://jruby.org/2017/12/07/jruby-9-1-15-0.html
```ruby
$ rbenv install jruby-9.1.15.0
Downloading jruby-dist-9.1.15.0-bin.tar.gz...
-> https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.1.15.0/jruby-dist-9.1.15.0-bin.tar.gz
Installing jruby-9.1.15.0...
/home/yahonda/.rbenv/plugins/ruby-build/bin/ruby-build: line 718: warning: command substitution: ignored null byte in input
/home/yahonda/.rbenv/plugins/ruby-build/bin/ruby-build: line 718: warning: command substitution: ignored null byte in input
Installed jruby-9.1.15.0 to /home/yahonda/.rbenv/versions/jruby-9.1.15.0
[yahonda@li1273-210 ruby-build (jruby91150)]$ rbenv global jruby-9.1.15.0
[yahonda@li1273-210 ruby-build (jruby91150)]$ ruby -v
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 OpenJDK …
```
=> Add JRuby 9.1.15.0

share/ruby-build/2.2.9, share/ruby-build/2.3.6, share/ruby-build/2.4.3, share/ruby-build/2.5.0-rc1
[CVE-2017-17405: Command injection vulnerability in Net::FTP](https://www.ruby-lang.org/en/news/2017/12/14/net-ftp-command-injection-cve-2017-17405/)
- [Ruby 2.2.9 Released
](https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-2-9-released/)
- [Ruby 2.3.6 Released](https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-3-6-released/)
- [Ruby 2.4.3 Released](https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-4-3-released/)
- [Ruby 2.5.0-rc1 Released](https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-5-0-rc1-released/)
=> Add 2.4.3, 2.3.6, 2.2.9, and 2.5.0-rc1

bin/ruby-build
rbenv install crashes on Solaris with an empty log file. Adding support
for the proper Solaris getconf call in num_cpu_cores fixed it. Tested
and working under OmniOS CE r151024.
=> Fix rbenv install on Solaris / Illumos

share/ruby-build/2.6.0-preview1
Ruby 2.6.0-preview1 has been released.
https://www.ruby-lang.org/en/news/2018/02/24/ruby-2-6-0-preview1-released/
=> Add definition for Ruby 2.6.0-preview1

share/ruby-build/jruby-9.1.16.0
JRuby 9.1.16.0 has been released.
http://jruby.org/2018/02/21/jruby-9-1-16-0.html
=> Add JRuby 9.1.16.0

share/ruby-build/2.2.10, share/ruby-build/2.3.7, share/ruby-build/2.4.4, share/ruby-build/2.5.1
These Rubies has been released.
- https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/
- https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/
- https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/
- https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-2-10-released/
=> Add definition for Ruby 2.5.1, 2.4.4, 2.3.7 and 2.2.10

bin/ruby-build, share/ruby-build/2.2.0, share/ruby-build/2.2.0-dev, share/ruby-build/2.2.0-preview1, share/ruby-build/2.2.0-preview2, share/ruby-build/2.2.0-rc1, share/ruby-build/2.2.1, share/ruby-build/2.2.10, share/ruby-build/2.2.2, share/ruby-build/2.2.3, share/ruby-build/2.2.4, share/ruby-build/2.2.5, share/ruby-build/2.2.6, share/ruby-build/2.2.7, share/ruby-build/2.2.8, share/ruby-build/2.2.9
(Awaiting Ruby 2.2 EOL at the end of March 2018.)
=> Ruby 2.2 reaches end of life on 2018-03-31

share/ruby-build/jruby-9.1.17.0
JRuby 9.1.17.0 has been released.
http://jruby.org/2018/04/23/jruby-9-1-17-0
=> Add definition for JRuby 9.1.17.0

share/ruby-build/jruby-9.2.0.0, share/ruby-build/jruby-9.2.1.0-dev
JRuby 9.2.0.0 has been released.
http://jruby.org/2018/05/24/jruby-9-2-0-0
=> Add definition for JRuby 9.2.0.0 and JRuby 9.2.1.0-dev

README.md, bin/ruby-build, share/ruby-build/truffleruby-1.0.0-rc2, test/build.bats, test/definitions.bats
Hello,
Here is a PR to add [TruffleRuby](https://github.com/oracle/truffleruby) to ruby-build.
I tried to keep the logic as simple as possible, and to update all relevant places mentioning other implementations.
I tested it locally and it seems to work well.
I also added a couple tests for the new logic.
This is a fully open-source version of TruffleRuby, corresponding to a subset of the Community Edition of GraalVM (See http://www.graalvm.org/downloads/)
It includes the [`native` configuration](https://github.com/oracle/truffleruby#truffleruby-configurations) only, not the `JVM` configuration, so there is no JVM involved.
=> Add TruffleRuby to ruby-build

bin/ruby-build, test/build.bats
* TruffleRuby already checks for LLVM itself when it needs it and looks up more paths to find the LLVM executables `clang` and `opt` (TruffleRuby also looks up in Homebrew and MacPorts directories on macOS).
* It's also needlessly restrictive for Homebrew and MacPorts (forcing the LLVM executables to be in `PATH`), so it should be removed.
* See https://github.com/oracle/truffleruby/issues/1386.
A similar PR was merged to RVM (https://github.com/rvm/rvm/pull/4427).
cc @hsbt
=> Remove early check for LLVM when installing TruffleRuby

share/ruby-build/truffleruby-1.0.0-rc5
* No 1.0.0-rc4 as that was a Graal JavaScript-only release.
cc @hsbt
=> Add definition for TruffleRuby 1.0.0-rc5

bin/ruby-build
This should solve https://github.com/rbenv/ruby-build/commit/d155b41e#commitcomment-30215955.
Renaming is needed for TruffleRuby, so just reverting the commit is not enough.
Specifically, https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc5/truffleruby-1.0.0-rc5-linux-amd64.tar.gz contains a toplevel directory `truffleruby-1.0.0-rc5-linux-amd64` which is not the same as `$package_name` which is `truffleruby-1.0.0-rc5`
So in this PR, I rename the extracted directory if it is not the same as `$package_name`
* make_package() assumes the archive was extracted to $package_name.
* fetch_tarball() does not check the name of the toplevel directory in
the archive, so rename after if it's not exactly "$package_name".
@mislav @xaque208 Please review this PR.
=> More portable rename after tarball extraction

README.md, bin/ruby-build, test/build.bats, test/cache.bats, test/checksum.bats, test/fetch.bats, test/mirror.bats, test/test_helper.bash
This allows users to choose appropriate HTTP client for ruby-build based on environment variable of `RUBY_BUILD_HTTP_CLIENT`. Since rbenv is based on shim script architecture, checking some command's availability based on the visibility in `$PATH` (e.g. `type aria2c`) is not actually appropriate way to do so.
The issue was originally reported as pyenv/pyenv#1126 that there was some problem in `aria2c` package of FreeBSD and `python-build` was always preferred to use it since it was on the top of the list. I think similar issue can happen with `ruby-build` too. This provides users to prepare some workaround for situations like that.
=> Allow overriding HTTP client type based on environment variable of `RUBY_BUILD_HTTP_CLIENT`

share/ruby-build/2.5.3
Hi,
Add install target 2.5.3 for https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/
=> Add MRI 2.5.3.

bin/ruby-build
This will allow other package managers that rely on ruby-build (i.e. https://github.com/asdf-vm/asdf-ruby) to update to the latest version so users can download Ruby 2.5.3
Fixes #1243
=> Bump version to 20181019

.travis.yml, test/test_helper.bash
Fixes #1056
PR #1038, specifically https://github.com/rbenv/ruby-build/pull/1038/files#diff-2b060f35496217f5f6b474e5552c11e2L6
broke the test suite on macOS.
This is because including `/usr/local/bin` in `PATH` makes
homebrew packages available to the tests, in particular readline.
Since ruby-build will prefer homebrew readline if available, making it
available in the tests will break any assertions that assume it _won't_
be available.
This PR also enables the test suite to run on macOS on Travis to prevent
regressions. The enabling of travis is the first commit, such that the
build can be seen to fail before the fix in the second commit.
=> Fix tests on macOS

bin/ruby-build
_Please go easy on me, I'm a first time contributor to the xenv suite of tools_ 🙇
I was trying to install Ruby 1.8.7 on macOS Mojave today and found that this message was out of date. `brew/taps` complains it no longer exists and the `apple-gcc42` package complains it hasn't worked on the last 4 macOS releases. Installing this gcc package did make `rbenv instal 1.8.7-p375` work for me (though I can't speak for whether or not it will link SSL correctly, basic Ruby scripts seem to work)
=> Update EOL Ruby message for macOS > 10.9 Mavericks

share/ruby-build/jruby-9.2.4.1
JRuby 9.2.4.1 has been released.
https://www.jruby.org/2018/11/28/jruby-9-2-4-1
=> Add definition for JRuby 9.2.4.1

share/ruby-build/2.6.0-rc2
https://www.ruby-lang.org/en/news/2018/12/15/ruby-2-6-0-rc2-released/
Successfully installed on macOS Mojave:
```
rbenv install 2.6.0-rc2
ruby-build: use openssl from homebrew
Downloading ruby-2.6.0-rc2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.0-rc2.tar.bz2
Installing ruby-2.6.0-rc2...
ruby-build: use readline from homebrew
Installed ruby-2.6.0-rc2 to /Users/frank/.rbenv/versions/2.6.0-rc2
```
=> add ruby 2.6.0-rc2

share/ruby-build/2.6.0
Ruby 2.6.0 has been released.
https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/
=> Add definition for Ruby 2.6.0

share/ruby-build/jruby-9.2.6.0
* JRuby 9.2.6.0 has been released.
* https://www.jruby.org/2019/02/11/jruby-9-2-6-0.html
=> Add JRuby 9.2.6.0

share/ruby-build/2.5.4, share/ruby-build/2.6.2
Ruby [2.5.4](https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-5-4-released/) and [2.6.2](https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-6-2-released/) have been released.
=> Add support for ruby 2.5.4 and 2.6.2

share/ruby-build/2.4.6
Ruby 2.4.6 has been released.
https://www.ruby-lang.org/en/news/2019/04/01/ruby-2-4-6-released/
=> Add definition for Ruby 2.4.6

share/ruby-build/jruby-9.2.7.0
JRuby 9.2.7.0 has been released.
https://www.jruby.org/2019/04/09/jruby-9-2-7-0
=> Add definition for JRuby 9.2.7.0

share/ruby-build/mruby-2.0.1
mruby 2.0.1 was released on April 4th, 2019.
https://github.com/mruby/mruby/releases/tag/2.0.1
=> Add definition for mruby 2.0.1

share/ruby-build/2.6.3
Ruby 2.6.3 has been released.
https://www.ruby-lang.org/en/news/2019/04/17/ruby-2-6-3-released
=> Add definition for Ruby 2.6.3

share/ruby-build/2.7.0-preview1
Released today:
https://www.ruby-lang.org/en/news/2019/05/30/ruby-2-7-0-preview1-released/
Also bumped OpenSSL to 1.1.1c since it hadn't been upgraded in a while:
https://www.openssl.org/news/cl111.txt
OpenSSL 1.1.1c was released on May 28th, 2019
=> Add CRuby 2.7.0-preview1

bin/ruby-build
`ruby-build: use readline from homebrew`
to
`ruby-build: using readline from homebrew`
`ruby-build: use libyaml from homebrew`
to
`ruby-build: using libyaml from homebrew`
And
`ruby-build: use openssl from homebrew`
To
`ruby-build: using openssl from homebrew`
=> Typo: Using readline from homebrew

share/ruby-build/2.7.0-dev
Today we switched ruby.git's default branch from "trunk" to "master":
https://bugs.ruby-lang.org/issues/15843
And the former "Ruby trunk" redmine project was renamed to ["Ruby master"](https://bugs.ruby-lang.org/projects/ruby-trunk) as well.
As trunk branch will be terminated on Jan 1st, 2020, we should use master branch for building 2.7.0-dev.
On my local environment, this branch worked like:
```
$ rbenv install 2.7.0-dev
Cloning https://github.com/ruby/ruby.git...
Installing ruby-master...
Installed ruby-master to /home/k0kubun/.rbenv/versions/2.7.0-dev
$ rbenv shell 2.7.0-dev
$ ruby -v
ruby 2.7.0dev (2019-06-30T16:05:29Z master dbe834ab5a) [x86_64-linux]
```
=> Use master branch of ruby.git for 2.7.0-dev

share/ruby-build/jruby-9.2.8.0
Closes #1335.
JRuby 9.2.8.0 has been released.
https://www.jruby.org/2019/08/12/jruby-9-2-8-0.html
=> Add definition for JRuby 9.2.8.0

share/ruby-build/2.6.4
Ruby 2.6.4 has been released.
https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/
=> Add definition for Ruby 2.6.4

share/ruby-build/2.4.7, share/ruby-build/2.5.6
These Rubies has been released.
- https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-5-6-released/
- https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-4-7-released/
=> Add definition for Ruby 2.5.6 and 2.4.7

share/ruby-build/2.6.5
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/
=> Add ruby 2.6.5

share/ruby-build/2.4.8
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-4-8-released/
=> Add Ruby 2.4.8

share/ruby-build/2.5.7
https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-5-7-released/
=> Add Ruby 2.5.7

bin/ruby-build
ruby-build formula [depends on openssl@1.1](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ruby-build.rb#L11), let’s look for that version
=> Look for Homebrew openssl@1.1

share/ruby-build/2.4.9
https://www.ruby-lang.org/en/news/2019/10/02/ruby-2-4-9-released/
Definition updated from the 2.4.8 one.
=> Add definition for Ruby 2.4.9.

README.md
I found the documentation on how to install ruby from a mirrored URL extremely unclear and found issues from folks who had also had that problem. This PR adds an example of a package downloaded from cache.ruby-lang.org and its corresponding download url on a mirror.
=> Add example of mirrored URL.

share/ruby-build/2.7.0-preview2
Ruby 2.7.0-preview2 has been released.
https://www.ruby-lang.org/en/news/2019/10/22/ruby-2-7-0-preview2-released/
=> Add definition for Ruby 2.7.0-preview2

bin/ruby-build
Detecting `$striplevel` relies on a git-specific line, so it is now made
to not depend on a git-specific match that is reliably present in all
patch formats.
Fixes #1159
=> Handle non-git patches

bin/ruby-build
`ruby-build` already does a lot of work to make sure that the version of ruby you're installing has the correct version of openssl also installed. Looking for any version of openssl installed by Homebrew is problematic for a few reasons:
- The user may have an incompatible version installed
- The user may not know that a particular version of openssl has been installed by Homebrew
- The openssl version split now makes this logic more difficult to maintain for all versions of ruby that `ruby-build` can install
Let's stop looking for any version of Homebrew's openssl by default so that the user always gets a working version of the ruby they're installing. Advanced users can use the `RUBY_CONFIGURE_OPTS="--with-openssl-dir=/my-openssl-directory"` option if they don't want to install the …
=> Don’t look for Homebrew openssl

bin/ruby-build
as an workaround for Ruby bug 16331: https://bugs.ruby-lang.org/issues/16331
Due to this bug, build will fail with FreeBSD's make after #1368.
The bug is already fixed in MRI upstream but GNU make is still required
when building older releases of Ruby. Use GNU make rather than switching
make/gmake depending of Ruby version.
See also: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241633
=> Set default MAKE=gmake on FreeBSD again

share/ruby-build/mruby-2.1.0
mruby 2.1.0 was released on November 19, 2019:
http://mruby.org/releases/2019/11/19/mruby-2.1.0-released.html
https://github.com/mruby/mruby/releases/tag/2.1.0
=> Add definition for mruby 2.1.0

bin/ruby-build, script/update-truffleruby, share/ruby-build/truffleruby-1.0.0-rc10, share/ruby-build/truffleruby-1.0.0-rc11, share/ruby-build/truffleruby-1.0.0-rc12, share/ruby-build/truffleruby-1.0.0-rc13, share/ruby-build/truffleruby-1.0.0-rc14, share/ruby-build/truffleruby-1.0.0-rc15, share/ruby-build/truffleruby-1.0.0-rc16, share/ruby-build/truffleruby-1.0.0-rc2, share/ruby-build/truffleruby-1.0.0-rc3, share/ruby-build/truffleruby-1.0.0-rc5, share/ruby-build/truffleruby-1.0.0-rc6, share/ruby-build/truffleruby-1.0.0-rc7, share/ruby-build/truffleruby-1.0.0-rc8, share/ruby-build/truffleruby-1.0.0-rc9, share/ruby-build/truffleruby-19.0.0, share/ruby-build/truffleruby-19.1.0, share/ruby-build/truffleruby-19.2.0, share/ruby-build/truffleruby-19.2.0.1, share/ruby-build/truffleruby-19.3.0, test/definitions.bats
Fixes https://github.com/oracle/truffleruby/issues/1818
* The openssl built by ruby-build was not used by TruffleRuby,
and causes https://github.com/oracle/truffleruby/issues/1818
* Improve error message when openssl from Homebrew is not available.
* Change the definition code so it checks the operating system too.
cc @hsbt
=> Use openssl from Homebrew for TruffleRuby on macOS

share/ruby-build/2.7.0-preview3
Ruby 2.7.0-preview3 has been released.
https://www.ruby-lang.org/en/news/2019/11/23/ruby-2-7-0-preview3-released/
And this PR has been verified using a modified checksum.
https://github.com/ruby/www.ruby-lang.org/pull/2284
=> Add definition for Ruby 2.7.0-preview3

share/ruby-build/2.7.0-rc1
Ruby 2.7.0-rc1 has been released.
https://www.ruby-lang.org/en/news/2019/12/17/ruby-2-7-0-rc1-released/
=> Add definition for Ruby 2.7.0-rc1

share/ruby-build/2.7.0
Ruby 2.7.0 has been released.
https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
=> Add definition for Ruby 2.7.0

bin/ruby-build, share/ruby-build/truffleruby-dev
* Uses the latest nightly, which is automatically built.
* I checked locally and it works well with:
`ruby-build truffleruby-dev ~/.rubies/truffleruby-dev`.
cc @hsbt @deepj 
Ref: https://github.com/oracle/truffleruby/issues/1483
=> Add truffleruby-dev to install the latest TruffleRuby nightly build

share/ruby-build/jruby-9.2.10.0
JRuby 9.2.10.0 has been released.
https://www.jruby.org/2020/02/18/jruby-9-2-10-0.html
=> Add definition for JRuby 9.2.10.0

share/ruby-build/jruby-9.2.11.0
JRuby 9.2.11.0 has been released.
https://www.jruby.org/2020/03/02/jruby-9-2-11-0
=> Add definition for JRuby 9.2.11.0

script/update-cruby, script/update-jruby
This PR adds update-mri and update-jruby scripts.
They are provided to update MRI and JRuby definition files.
These scripts are based on script/update-truffleruby.
https://github.com/rbenv/ruby-build/blob/v20200224/script/update-truffleruby
=> Add update-mri and update-jruby scripts

share/ruby-build/2.4.0, share/ruby-build/2.4.0-dev, share/ruby-build/2.4.0-preview1, share/ruby-build/2.4.0-preview2, share/ruby-build/2.4.0-preview3, share/ruby-build/2.4.0-rc1, share/ruby-build/2.4.1, share/ruby-build/2.4.10, share/ruby-build/2.4.2, share/ruby-build/2.4.3, share/ruby-build/2.4.4, share/ruby-build/2.4.5, share/ruby-build/2.4.6, share/ruby-build/2.4.7, share/ruby-build/2.4.8, share/ruby-build/2.4.9, share/ruby-build/2.5.8, share/ruby-build/2.6.6, share/ruby-build/2.7.1
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-4-10-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-5-8-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/
https://www.ruby-lang.org/en/downloads/branches/
=> add definition 2.4.10, 2.5.8, 2.6.6, 2.7.1 and ruby 2.4 EOL

share/ruby-build/jruby-9.2.11.1
JRuby 9.2.11.1 has been released.
https://www.jruby.org/2020/03/25/jruby-9-2-11-1
=> Add definition for JRuby 9.2.11.1

bin/ruby-build
Hello, would you mind rolling a new release? There were [new definitions added](https://github.com/rbenv/ruby-build/commit/d45c4ed624812e27317c98b174bd4debd39a80f7) for ruby releases that addressed security vulnerabilities.
- [2.4.10](https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-4-10-released/)
- [2.5.8](https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-5-8-released/)
- [2.6.6](https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/)
- [2.7.1](https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/)
=> ruby-build 20200401

bin/ruby-build, test/definitions.bats
Suggested by mislav: https://github.com/rbenv/ruby-build/pull/1402#discussion_r389060742
> I wonder should we substitute "built-in" with something like "all
> available definitions". Since ruby-build will additionally pick up
> definitions found under the paths listed in RUBY_BUILD_DEFINITIONS,
> these definitions will get listed even if they are not "built-in".
> Therefore, "built-in" feels like a misnomer here.
Searched by `git grep built-in`.
=> s/all built-in definitions/all available definitions/

share/ruby-build/2.5.0, share/ruby-build/2.5.0-dev, share/ruby-build/2.5.0-preview1, share/ruby-build/2.5.0-rc1, share/ruby-build/2.5.1, share/ruby-build/2.5.2, share/ruby-build/2.5.3, share/ruby-build/2.5.4, share/ruby-build/2.5.5, share/ruby-build/2.5.6, share/ruby-build/2.5.7, share/ruby-build/2.5.8
merge when https://github.com/ruby/www.ruby-lang.org/pull/2410 and https://github.com/ruby/www.ruby-lang.org/pull/2420 get released
=> mark ruby 2.5 as security maintenance

bin/rbenv-install, bin/ruby-build, test/definitions.bats, test/rbenv.bats
As time passes, list of available ruby versions is growing. However, I think ordinary users hardly install ancient versions such as Ruby 1.8 and Ruby 1.9. Now `rbenv install -l` became too big and is filled up with obsolete unused versions.
I implemented new options to show only supported versions. 
* `rbenv install -L (--list-exclude-eol)`
* `ruby-build --definitions-exclude-eol`
I used `warn_eol` `warn_unsupported` flag to determine if the version is EoL'ed.
Now I get significantly compact list.
```
% ruby-build --definitions | wc -l
463
% ruby-build --definitions-exclude-eol | wc -l
186
```
Also I can easily know which versions are supported. I believe this feature is helpful for most users.
```
% ruby-build --definitions-exclude-eol |grep ^'[0-9]'
2.5.0-dev
2.5.0-preview1
2.5.0-rc1 …
```
=> The list `rbenv install -l` is too long, show latest stable releases by default

bin/ruby-build
The existing install function wiped out the prefix that `build_package_copy`
copied the binaries to. The subsequently created symlinks point to files
that don't exist on disk.
cc @deepj 
I'm hoping that ruby-build can push a release after merging this fix. The current release results in:
```console
$ ruby
rbenv: ruby: command not found
The `ruby' command exists in these Ruby versions:
2.6.3
2.6.5
2.6.6
```
=> Fix artichoke-dev installer

bin/ruby-build
When installing jruby, and using bash 4.4 or higher, you get the following warning:
```
$ rbenv install jruby-9.2.11.1 
Downloading jruby-bin-9.2.11.1.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/f10449c82567133908e5e1ac076438307a7f0916f617f40fa314b78873a195dc
Installing jruby-9.2.11.1...
/home/deivid/.rbenv/plugins/ruby-build/bin/ruby-build: line 739: warning: command substitution: ignored null byte in input
/home/deivid/.rbenv/plugins/ruby-build/bin/ruby-build: line 739: warning: command substitution: ignored null byte in input
Installed jruby-9.2.11.1 to /home/deivid/.rbenv/versions/jruby-9.2.11.1
```
This PR explicitly removes the null byte bash is complaining about.
But other approach could be to explicitly exclude "binary binstubs" from the check. In particular, this warning is …
=> Fix a bash 4.4 warning when installing jruby

bin/ruby-build
https://en.wikipedia.org/wiki/MacOS_Big_Sur
stop hardcoding `OS X` since `macOS Big Sur` version no. is 11.0
=> compatible with macOS 11

bin/ruby-build
See #1459.
This way avoids moving and removing files.
=> Fix installation of truffleruby+graalvm on macOS

share/ruby-build/jruby-9.2.13.0
JRuby 9.2.13.0 has been released.
https://www.jruby.org/2020/08/03/jruby-9-2-13-0
=> Add definition for JRuby 9.2.13.0

share/ruby-build/3.0.0-preview1
https://www.ruby-lang.org/en/news/2020/09/25/ruby-3-0-0-preview1-released/
=> Add definition for 3.0.0-preview1

share/ruby-build/2.7.2
Ruby 2.7.2 has been released.
https://www.ruby-lang.org//en/news/2020/10/02/ruby-2-7-2-released/
=> Add definition for Ruby 2.7.2

share/ruby-build/maglev-1.0.0, share/ruby-build/maglev-1.1.0-dev, share/ruby-build/maglev-2.0.0-dev
as the last commit of mavlev is over 3 years ago
Discussed at: https://github.com/rbenv/ruby-build/pull/1402#issuecomment-596162716
=> mark maglev as EoL

README.md, bin/ruby-build, test/mirror.bats
When using a mirror, `ruby-build` requires the package is located at `$RUBY_BUILD_MIRROR_URL/<SHA2>`, which is not a generic case.
[Here](https://www.ruby-lang.org/en/downloads/mirrors/) list all mirror sites of ruby source, and most of them provide the tarball with name format like `http://host/pub/ruby/2.7/2.7.1.tar.bz2`. To benefit from more mirror sites, and also keep compatibility, I propose adding another variable (which can be named as `RUBY_BUILD_MIRROR_PACKAGE_URL`) to specify the complete mirror URL. So a user can use it like this:
```
$ RUBY_BUILD_MIRROR_PACKAGE_URL=https://cache.ruby-china.com/pub/ruby/2.7/ruby-2.7.1.tar.bz2 asdf install ruby 2.7.1
```
Fix #1032. As [this comment](https://github.com/rbenv/ruby-build/issues/1032#issuecomment-266220709) said, the download speed …
=> Support specifying the complete mirror URL

.github/workflows/ci.yml, .travis.yml
Because Travis CI add a rate-limit for OSS project. I'm waiting with 30 minutes for invoking all of jobs now.
=> Split macOS test to GitHub Actions

share/ruby-build/jruby-9.2.14.0
Resolves #1503.
JRuby 9.2.14.0 has been released.
https://www.jruby.org/2020/12/08/jruby-9-2-14-0
=> Add definition for JRuby 9.2.14.0

share/ruby-build/3.0.0-rc1
See: https://www.ruby-lang.org/en/news/2020/12/20/ruby-3-0-0-rc1-released/
https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0-rc1.tar.gz
```
SIZE: 19488885
SHA1: 34ede2128a90ef3217d9cab9efcdf20fc444f67c
SHA256: e1270f38b969ce7b124f0a4c217e33eda643f75c7cb20debc62c17535406e37f
SHA512: 798926db82d27366b39be97556ac5cb322986b96df913c398449bd3ece533e484a3047fe35e7a6241dfbd0f7da803438f5b04b805b33f95c73e3e41d0bb51183
```
=> Add 3.0.0 RC1

share/ruby-build/artichoke-dev
Closes #1701
ARM
```
$ uname -m
arm64
$ ruby-build artichoke-dev ~/.rubies/artichoke-dev
Downloading artichoke-nightly-aarch64-apple-darwin.tar.gz...
-> https://github.com/artichoke/nightly/releases/latest/download/artichoke-nightly-aarch64-apple-darwin.tar.gz
Installing artichoke-nightly...
Installed artichoke-nightly to ~/.rubies/artichoke-dev
$ ~/.rubies/artichoke-dev/bin/ruby --version
artichoke 0.1.0-pre.0
$ ~/.rubies/artichoke-dev/bin/ruby -e "puts RUBY_PLATFORM"
aarch64-apple-darwin
```
x86_64
```
$ uname -m
x86_64
$ ruby-build artichoke-dev ~/.rubies/artichoke-dev
Downloading artichoke-nightly-x86_64-apple-darwin.tar.gz...
-> https://github.com/artichoke/nightly/releases/latest/download/artichoke-nightly-x86_64-apple-darwin.tar.gz
Installing artichoke-nightly...
Installed …
```
=> Allow to install Artichoke's ARM builds on macOS

jruby-9.2.15.0
JRuby 9.2.15.0 was released today (https://www.jruby.org/2021/02/24/jruby-9-2-15-0.html). I believe this is the file that would make it available for ruby-build env.
=> adds jruby 9.2.15.0

share/ruby-build/jruby-9.2.17.0
It was released yesterday: https://www.jruby.org/2021/03/29/jruby-9-2-17-0.html
=> Add JRuby 9.2.17.0 definition

bin/ruby-build
Because autoconf-2.71+ is incompatible with 2.69 or before.
=> Use autoreconf -i instead of autoconf 

share/ruby-build/2.5.9, share/ruby-build/2.6.7, share/ruby-build/2.7.3, share/ruby-build/3.0.1
Ruby 3.0.1, 2.7.3, 2.6.7, 2.5.9 has been released.
https://www.ruby-lang.org/en/news/2021/04/05/ruby-3-0-1-released/
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-7-3-released/
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-6-7-released/
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-5-9-released/
=> Added 3.0.1, 2.7.3, 2.6.7, 2.5.9

share/ruby-build/2.5.0, share/ruby-build/2.5.0-dev, share/ruby-build/2.5.0-preview1, share/ruby-build/2.5.0-rc1, share/ruby-build/2.5.1, share/ruby-build/2.5.2, share/ruby-build/2.5.3, share/ruby-build/2.5.4, share/ruby-build/2.5.5, share/ruby-build/2.5.6, share/ruby-build/2.5.7, share/ruby-build/2.5.8, share/ruby-build/2.5.9
This PR updates the warning for Ruby 2.5.x to indicate, that it is no longer supported.
Ruby 2.5 is EOL from 2021-03-31.
=> warn eol for ruby 2.5

share/ruby-build/truffleruby+graalvm-21.1.0
* Unfortunately the files were changed and reuploaded as there was an
issue with the gu (GraalVM Component Updater) catalog URL.
=> Fix hashes for TruffleRuby GraalVM 21.1.0

share/ruby-build/truffleruby-21.1.0
* Unfortunately the original builds were based on incorrect JDK versions,
these new hashes represent the correct builds based on JDK11.
=> Fix hashes for TruffleRuby 21.1.0

share/ruby-build/jruby-dev
* Uses the latest nightly, which is automatically built.
This is a shameless copy of https://github.com/rbenv/ruby-build/pull/1405.
=> Add jruby-dev

share/ruby-build/2.6.8, share/ruby-build/2.7.4, share/ruby-build/3.0.2
Ruby 2.6.8, 2.7.4, 3.0.2 has been released.
https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-6-8-released/
https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released/
https://www.ruby-lang.org/en/news/2021/07/07/ruby-3-0-2-released/
=> Add Ruby 2.6.8, 2.7.4, 3.0.2

bin/ruby-build, test/build.bats
* Only do clean_prefix_path for TruffleRuby and rename for clarity,
since the logic is now TruffleRuby-specific.
* Alternative to https://github.com/rbenv/ruby-build/pull/1783, cc @casperisfine
The error message looks like:
```
$ bin/ruby-build truffleruby-dev /usr/local
Downloading truffleruby-head-ubuntu-18.04.tar.gz...
-> https://github.com/ruby/truffleruby-dev-builder/releases/latest/download/truffleruby-head-ubuntu-18.04.tar.gz
Installing truffleruby-head...
ERROR: cannot install TruffleRuby to /usr/local, which does not look like a valid TruffleRuby prefix
TruffleRuby only supports being installed to a not existing directory or replacing an existing TruffleRuby installation
See https://github.com/oracle/truffleruby/issues/1389 for details
BUILD FAILED (OS VERSION using ruby-build …
```
=> Ensure it is safe to remove the prefix path for TruffleRuby or error

script/update-truffleruby, script/update-truffleruby-graalvm, share/ruby-build/truffleruby+graalvm-21.2.0, share/ruby-build/truffleruby-21.2.0, share/ruby-build/truffleruby-dev
* Fixes #1786
The linux-aarch64 standalone should soon be available at https://github.com/oracle/truffleruby/releases/tag/vm-21.2.0, so I will wait for that.
=> TruffleRuby 21.2+ adds support for linux-aarch64

share/ruby-build/truffleruby-21.2.0.1
https://github.com/oracle/truffleruby/releases/tag/vm-21.2.0.1
For truffleruby+graalvm it will automatically pick the ruby 21.2.0.1 installable when installing `truffleruby+graalvm-21.2.0`, so no need to change anything there.
=> Add TruffleRuby 21.2.0.1

share/ruby-build/yjit-dev
YJIT builds just like regular `ruby-head`, just pointing to a different repo.
I think it would be useful to have it available for people who want to try they apps against it.
=> Add a definition for yjit-dev

bin/ruby-build, test/build.bats
* Fixes https://github.com/rbenv/ruby-build/issues/1798
* OpenJDK 17 reports:
$ java -version
openjdk version "17" 2021-09-14
There is no dot in the version, so we need to only use the first match from grep -o.
* Clarify it is a minimum required java version, not an exact version.
=> Fix version check for Java 17

script/update-jruby, share/ruby-build/jruby-9.3.0.0
Following up from https://github.com/ruby/setup-ruby/issues/220...
The S3 URLs used by ruby-build are still maintained, but we prefer that apps and tools switch to the Maven URLs. They are mirrored and federated and not dependent on us maintaining our own data store.
Pinging @enebo to see if we should make this change for earlier versions, perhaps back to the earliest version for which we push jruby-dist?
=> Prefer maven URLs going forward

share/ruby-build/yjit-dev
YJIT has been merged with upstream CRuby and the repo used by ruby-build is no longer maintained properly.
At this point the best way to build YJIT is with 3.1.0-dev or similar head-of-CRuby-master.
cc: @casperisfine
=> Remove yjit-dev

.github/workflows/release.yml
Version 1.14 [has a bug](https://github.com/mislav/bump-homebrew-formula-action/issues/25) that prevents ruby-build to be pushed to homebrew and rubyists to enjoy the latest flavor of ruby, [as we can see here ](https://github.com/rbenv/ruby-build/runs/4631985764?check_suite_focus=true)
This PR fixes the version to the previous one to avoid this issue
Edit: just realised the build seems to have been retried and worked, maybe the error is just transient
=> Fix version of mislav/bump-homebrew-formula-action to avoid bug

share/ruby-build/3.2.0-dev
Ruby 3.1+ support OpenSSL 3.x. I test it on the Ruby 3.2. After that, We may apply it to Ruby 3.0 series.
=> Use OpenSSL 3.x after Ruby 3.2

.github/workflows/release.yml
The v1 branch is now fixed. Ref. https://github.com/rbenv/ruby-build/pull/1839
Thanks @Intrepidd
=> Update bump-homebrew-formula action

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement.md
This adds issue templates for this repository. It defines 3 categories of reports:
- "bug"
- "enhancement" (feature requests) 
- "BUILD FAILED" - instructs people to post to the Discussions section instead of filing Issues.
The goal is to redirect people to Discussions instead of Issues when seeking support for various build failures which, historically, are rarely caused by bugs in ruby-build code.
=> Add issue templates

share/ruby-build/3.2.0-preview1
Ruby 3.2.0-preview1 has been released.
https://www.ruby-lang.org/en/news/2022/04/03/ruby-3-2-0-preview1-released/
This PR specifies the same OpenSSL version (3.0.2) as 3.2.0-dev.
https://github.com/rbenv/ruby-build/blob/v20220324/share/ruby-build/3.2.0-dev#L1
=> Add definition for Ruby 3.2.0-preview1

bin/ruby-build
Fix for #1955 #1911 
The check to prevent deleting user files during clean_prefix_path by disallowing installs into existing directories that weren't earlier truffleruby installs broke asdf installs, as asdf always creates an empty directory before installing.
This fix adds a second exception to the existing directory case when that directory is empty. The check is done by testing the string length of ls output. The logic was manually tested against non-existing directories, existing empty directories, existing non-empty directories in general, and existing non-empty directories that contained a file named "bin/truffleruby".
I also copied the file over my existing asdf version of ruby-build and made sure that it successfully installed truffleruby.
=> Allow truffleruby to install in an existing empty directory

bin/ruby-build
* See https://github.com/openssl/openssl/issues/8170
* The install_sw target exists since 1.0.0 or earlier:
https://github.com/openssl/openssl/blob/OpenSSL_1_0_0-stable/Makefile.org
=> Skip building docs when building openssl

bin/ruby-build
Prior commit attempts to shorten install by omitting documentation install,
however an additional target is needed to get the conf dirs for capturing the
PEMs et al.
Solves issue mentioned in [discussion 1972](https://github.com/rbenv/ruby-build/discussions/1972).
Related to https://github.com/rbenv/ruby-build/pull/1967
=> Re-enable ssldir creation target for openssl install

share/ruby-build/truffleruby+graalvm-dev, share/ruby-build/truffleruby-dev
@eregon there are native builds of TruffleRuby available in Graal build repo. So let's download them from there for dev at least
=> Allow to download truffleruby-dev builds for Darwin-arm64 and Linux-aarch64

bin/ruby-build, share/ruby-build/picoruby-3.0.0
This is the first time to send a PR of adding PicoRuby to ruby-build, so I show you how it's working on my local computer:
In addition to the above executables (`picoruby` and `picoirb`), `picorbc` which is the PicoRuby compiler executable will be installed, too.
This version number `3.0.0` corresponds to the mruby's version which means a VM code generated by the picorbc 3.0.0 runs on mruby virtual machine 3.0.0 like this:
=> Add picoruby-3.0.0

share/ruby-build/3.1.0, share/ruby-build/3.1.0-dev, share/ruby-build/3.1.0-preview1, share/ruby-build/3.1.1, share/ruby-build/3.1.2
Related with https://github.com/rbenv/ruby-build/issues/1998#issuecomment-1180698666
Ruby 3.1.x already support OpenSSL 3.0. There is no reason why Ruby 3.1 use OpenSSL 1.1.
=> Use OpenSSL 3.x with Ruby 3.1.x

bin/ruby-build, share/ruby-build/3.2.0-dev
This PR is a followup to https://github.com/rbenv/ruby-build/issues/1970. It adds build_package_enable_yjit.
If YJIT is explicitly enabled or disabled in RUBY_CONFIGURE_OPTS, enable_yjit should do nothing.
If YJIT is not specified and rustc is 1.6 or higher, it should print a message and enable YJIT.
If YJIT is not specified and rustc is not found or too old, it should print a "yjit disabled by default" message and do nothing else.
I've added the enable_yjit package to 3.2.0-dev only. In theory this could cause problems for 3.2.0 dev versions earlier than Rust-YJIT integration (19th April, CRuby SHA f90549). But it looks like 3.2.0-dev will only install latest master, not earlier random CRuby SHAs.
Rust-YJIT technically supports rustc 1.58+. But we said 1.60+ in the issue, so that's what …
=> For Ruby 3.2.0-dev, install YJIT by default if rustc 1.60+ is available

bin/ruby-build
Resolve https://github.com/rbenv/ruby-build/discussions/2009#discussioncomment-3146585
@mislav @eregon Can you review this? I'm not sure which location is the best for this workaround.
=> Apply patch for implicitly declaration error of OpenSSL 1.1.1q

bin/ruby-build
* `openssl version` can be another version than the header, for instance with
`apt-get install --no-install-recommends ca-certificates libssl1.0-dev` on Ubuntu 18.04:
https://github.com/rbenv/ruby-build/discussions/2014#discussioncomment-3224237
=> Only check the opensslv.h header to find the system openssl version

bin/ruby-build, test/test_helper.bash
* Fixes https://github.com/rbenv/ruby-build/issues/1721
=> Show the log file to make it easy to follow progress

bin/ruby-build
https://github.com/ruby/ruby/pull/6289 support arm64 arch with YJIT now.
/cc @noahgibbs
=> Re-enable YJIT with arm64

bin/ruby-build
Followed up https://github.com/rbenv/ruby-build/pull/2028
=> Enable YJIT only x86_64 and arm64

bin/ruby-build
@noahgibbs /cc @k0kubun 
YJIT supported rustc-1.58.1+. I suggest relaxing its version on ruby-build because apt package manager of Ubuntu 20.04 and 22.04 provides rustc-1.59.0.
=> Relax rustc version to 1.58.1

share/ruby-build/3.2.0-preview2
https://www.ruby-lang.org/en/news/2022/09/09/ruby-3-2-0-preview2-released/
=> Added 3.2.0-preview2

.github/workflows/ci.yml, .github/workflows/mirror.yml, .github/workflows/release.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
Here is an example of the permissions in one of the workflows:
https://github.com/rbenv/ruby-build/runs/8282527096?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for each workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-git …
=> Add minimum GitHub token permissions for workflows

bin/ruby-build, script/test, test/build.bats
MRI's BigInt use GMP under the hood if available, and if not fallbacks to an homemade implementation with much worse performance.
Without GMP:
```
>> Benchmark.realtime { Integer('1' * (10 ** 7)) }
=> 13.80743500002427
```
With GMP
```
>> Benchmark.realtime { Integer('1' * (10 ** 7)) }
=> 0.4098639999865554
```
macOS not being a common production platform, it's not a huge deal but it would still preferable to compile with `gmp.h` if present.
I'd also suggest to print a warning if compiling on macOS and gmp isn't installed, but I don't know if it's desirable.
cc @eregon @hsbt
=> macOS: Use GMP from homebrew

bin/ruby-build
Fixed https://github.com/rbenv/ruby-build/issues/2043
I confirmed to work this with OpenSUSE leap 15.4.
=> Allow OPENSSL_VERSION_TEXT string match without last line for OpenSUSE

bin/rbenv-install, test/hooks.bats, test/rbenv.bats
Upon installing their first Ruby version on the system, the user may want to set it as their default; otherwise the default will remain "system" and any `gem install` attempts will fail with a permission error.
This suggestion is skipped if the user already has chosen an explicit default, even if it's "system".
Ref. https://github.com/rbenv/rbenv/issues/1424
=> Suggest `rbenv global` if there is no explicit global setting

bin/rbenv-install
This makes it easier to redirect `rbenv install -l` output without having to silence stderr to get rid of the extra notice.
Fixes https://github.com/rbenv/ruby-build/issues/2054
=> List output: only print stderr notice if printing to a terminal

script/release
- Uses `gh` (GitHub CLI) instead of `hub` to make the release
- Generates release notes on the server instead of locally
/cc @eregon @hsbt
=> Release with gh instead of with hub

share/ruby-build/2.6.0, share/ruby-build/2.6.1, share/ruby-build/2.6.10, share/ruby-build/2.6.2, share/ruby-build/2.6.3, share/ruby-build/2.6.4, share/ruby-build/2.6.5, share/ruby-build/2.6.6, share/ruby-build/2.6.7, share/ruby-build/2.6.8, share/ruby-build/2.6.9, share/ruby-build/2.7.0, share/ruby-build/2.7.1, share/ruby-build/2.7.2, share/ruby-build/2.7.3, share/ruby-build/2.7.4, share/ruby-build/2.7.5, share/ruby-build/2.7.6
Note: I wish we could somehow embed the support/EOL date into the build definition itself so that these warnings could automatically start printing when past the cutoff date instead of us having to ship updates to ruby-build.
Ref. #942
=> Mark Ruby 2.6 as EOL and 2.7 as "unsupported"

share/ruby-build/3.2.0-preview3
Ruby 3.2.0-preview3 has been released.
https://www.ruby-lang.org/en/news/2022/11/11/ruby-3-2-0-preview3-released/
=> Add definition for Ruby 3.2.0-preview3

bin/ruby-build, share/ruby-build/3.2.0-dev, share/ruby-build/3.2.0-preview2, share/ruby-build/3.2.0-preview3
Latest Ruby 3.2 development version now detects `rustc` on the system and automatically assumes `--enable-yjit` on susupported platforms unless `--disable-yjit` was explicitly passed. https://github.com/ruby/ruby/pull/6662
I propose that ruby-build does not attempt to duplicate this logic, but that it leaves it completely to Ruby's own build system.
Followup to https://github.com/rbenv/ruby-build/issues/1970 /cc @byroot @maximecb
=> Do not automatically enable YJIT nor attempt to detect rustc

script/update-truffleruby-graalvm, share/ruby-build/truffleruby+graalvm-dev
=> truffleruby+graalvm-dev builds are now based on Java 17

share/ruby-build/2.7.7, share/ruby-build/3.0.5, share/ruby-build/3.1.3
These Rubies have been released.
- https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-1-3-released/
- https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-0-5-released/
- https://www.ruby-lang.org/en/news/2022/11/24/ruby-2-7-7-released/
=> Add definition for Ruby 3.1.3, 3.0.5, and 2.7.7

share/ruby-build/3.2.0-rc1
Ruby 3.2.0 RC 1 has been released.
https://www.ruby-lang.org/en/news/2022/12/06/ruby-3-2-0-rc1-released/
=> Add definition for Ruby 3.2.0 RC 1

share/ruby-build/1.8.7-p375
=> svn.ruby-lang.org is shutdown now.

bin/ruby-build, share/ruby-build/1.9.2-p326
The ruby core team already shutdown svn.ruby-lang.org via https://github.com/rbenv/ruby-build/issues/2119
I removed svn feature and replace definition to use it.
=> Drop svn support

share/ruby-build/topaz-dev
Unfortunately, http://topazruby.com/ is 404 today.
=> http://topazruby.com/ is 404 now

share/ruby-build/3.2.1
https://www.ruby-lang.org/en/news/2023/02/08/ruby-3-2-1-released/
=> Add Ruby 3.2.1

share/ruby-build/truffleruby+graalvm-dev, share/ruby-build/truffleruby-dev
The current _truffleruby-dev_ builds are based on Ubuntu 18.04. Since Ubuntu 18.04 will be EOL in two months, we should switch over to Ubuntu 20.04 as our newest base.
Likewise, the _truffleruby+graalvm-dev_ installation URLs broke because Java 19 was not an LTS release and there are no longer snapshot builds based on Java 19. While Java 20 builds are available, we should just use Java 17 as that's the most recent Java LTS. As such, those URLs will be more stable; they won't change until the next Java LTS release.
=> Update TruffleRuby dev release URLs

bin/ruby-build, test/build.bats, test/compiler.bats, test/rbenv.bats, test/stubs/stub, test/test_helper.bash
closes #1928 
turns out there already was a test for this behaviour but it was falsely passing due to `needs_yaml` (that was run only from tests) was calling `use_homebrew_yaml` (which was otherwise not called in production)
Bash is not my native language and I've had very limited experience with BATS framework so there might be things I've done wrong :)
=> Automatically detect and link to Homebrew's libyaml

.github/workflows/mirror.yml
This is to stop people's security software from complaining about it.
Fixes https://github.com/rbenv/ruby-build/issues/2161
=> Remove AWS access key ID from version control

share/ruby-build/2.7.8, share/ruby-build/3.0.6, share/ruby-build/3.1.4, share/ruby-build/3.2.2
See security/release announcements for:
* [2.7.8](https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/)
* [3.0.6](https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-0-6-released/)
* [3.1.4](https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-1-4-released/)
* [3.2.2](https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-2-2-released/)
=> Add definitions for Ruby 2.7.8, 3.0.6, 3.1.4, 3.2.2

script/update-cruby
`sha256sum` is not by default installed on macOS, but `shasum` is. They function equivalently, as far as I can tell, so this PR introduces a seamless fallback onto `shasum` so macOS users can run `scripts/update-cruby`. 🙂
If desired, I can update the other scripts as well.
=> Fall back on shasum if sha256sum is unavailable

share/ruby-build/2.6.0-preview1, share/ruby-build/2.6.0-preview2, share/ruby-build/2.6.0-preview3, share/ruby-build/2.6.0-rc1, share/ruby-build/2.6.0-rc2, share/ruby-build/2.7.0, share/ruby-build/2.7.0-preview1, share/ruby-build/2.7.0-preview2, share/ruby-build/2.7.0-preview3, share/ruby-build/2.7.0-rc1, share/ruby-build/2.7.0-rc2, share/ruby-build/2.7.1, share/ruby-build/2.7.2, share/ruby-build/2.7.3, share/ruby-build/2.7.4, share/ruby-build/2.7.5, share/ruby-build/2.7.6, share/ruby-build/2.7.7, share/ruby-build/2.7.8
I added `warn_eol` flag to all of Ruby 2.7 versions and preview version of Ruby 2.6.
=> Mark EOL status to Ruby 2.6 and 2.7

bin/ruby-build, script/update-truffleruby-graalvm, share/ruby-build/truffleruby+graalvm-23.0.0-preview1
For this release it's packaged a bit differently, we have a GraalVM with JDK and already including the TruffleRuby component at https://github.com/oracle/truffleruby/releases/tag/vm-23.0.0-preview1.
=> Add TruffleRuby+GraalVM 23.0.0-preview1

share/ruby-build/3.3.0-preview1
https://www.ruby-lang.org/en/news/2023/05/12/ruby-3-3-0-preview1-released/
=> Added Ruby 3.3.0-preview1

script/update-truffleruby-graalvm, share/ruby-build/truffleruby+graalvm-23.0.0, share/ruby-build/truffleruby-23.0.0
* Use the new Oracle GraalVM distribution which uses the GFTC license as it is significantly faster than GraalVM CE and is free for development and production use.
* See https://medium.com/graalvm/whats-new-in-graalvm-languages-161527df3d76
=> Add TruffleRuby and TruffleRuby+GraalVM 23.0.0

share/ruby-build/truffleruby+graalvm-23.0.0, share/ruby-build/truffleruby-23.0.0
Follow-up of https://github.com/rbenv/ruby-build/pull/2207, it seems best to be explicit about the change of distribution.
=> Print a message about the new distribution and license when installing TruffleRuby 23.0

bin/ruby-build
Hello maintainers, 
Based on the request made by @sos4nt in the issue https://github.com/rbenv/ruby-build/issues/2224 I wanted to add the openssl version that is used by default by ruby-build. Printing it to the screen in the same way as the issue requester suggested, to the stdout. 
Let me know if you have any questions or concerns, it's my first PR to this project so all feedback is welcome!
Thanks
=> Show openssl version used from homebrew by default

bin/ruby-build
I was encountering some build issues on MicroOS and needed the actual exception message in order to pinpoint a workaround.
=> Display the actual error when testing for Ruby's openssl extension

bin/ruby-build, test/build.bats
Conditionally update rubygems only for JRuby 9.2.x. This allows the next step - installation of jruby-launcher gem - to succeed.
fixes https://github.com/rbenv/ruby-build/issues/2238
=> workaround jruby#7799 by updating rubygems for JRuby 9.2.x

share/ruby-build/truffleruby+graalvm-dev
* In TruffleRuby 23.1+, the GraalVM Updater (`gu`) is no longer available in GraalVM, instead JVM Standalones and Maven artifacts are provided to replace `gu`.
* See https://github.com/oracle/graal/issues/6855
=> Use the TruffleRuby JVM Standalones for truffleruby+graalvm-dev

bin/ruby-build, test/build.bats
This was set to gmake in https://github.com/rbenv/ruby-build/pull/1381 as a workaround for https://bugs.ruby-lang.org/issues/16331
YJIT builds in Ruby 3.3 previews require the use of BSD make on these platforms, and no supported version of MRI requires the use of gmake, so revert this.
JRuby continues to require gmake for jruby-launcher.
=> Set default MAKE=make on FreeBSD

bin/rbenv-install, bin/ruby-build, test/build.bats, test/compiler.bats, test/rbenv.bats, test/stubs/stub
Previously, optional flags for the Ruby `./configure` step were passed like this:
```sh
RUBY_CONFIGURE_OPTS="--disable-install-doc --with-openssl-dir=..." ruby-build <version> <destination>
```
However, it wasn't possible to use RUBY_CONFIGURE_OPTS to pass individual values that contain spaces, even when properly quoted. That is because RUBY_CONFIGURE_OPTS ignores quoting and has bash perform normal word splitting.
Now, in addition to RUBY_CONFIGURE_OPTS, both ruby-build and `rbenv install` accept the following syntax:
```sh
ruby-build <version> <destination> -- --disable-install-doc --with-openssl-dir="/path with spaces"
```
That is, any flags after `--` are forwarded as `./configure` flags when compiling Ruby. By using the new method, it is possible to supply any value, even those with …
=> Pass ruby configuration flags on the command line

bin/rbenv-install, bin/ruby-build
There was a clever, dynamic `[ ... ]` expression that was technically valid bash, but caused shellcheck to stop parsing from that point onward, resulting in it being unable to process most of `bin/ruby-build`. This fixes that, as well as takes care of all shellcheck warnings under the `bin/` directory.
I do not care about most shellcheck errors nor warnings under the `test/` directory.
=> Enable shellcheck parsing of ruby-build source

share/ruby-build/truffleruby-dev
* macos-arm64 runners recently became available for ruby/truffleruby-dev-builder.
* Those builds are more frequently updated than on graalvm-ce-dev-builds.
cc @nirvdrum
=> Use builds from ruby/truffleruby-dev-builder for truffleruby-dev on macos-arm64

README.md, bin/ruby-build
* And add RUBY_BUILD_IGNORE_CHECKSUM when it is expected the alternative URL has different contents.
This is useful for instance when testing a truffleruby release which is not published yet.
Then I need to use a custom URL, like:
```
RUBY_BUILD_MIRROR_PACKAGE_URL=https://github.com/my/url.tar.gz ruby-build truffleruby-23.1.0 ~/.rubies/truffleruby-test
```
I also want this to try dev builds at a different URL, hence this change.
(and those might have a different checksum too, see below)
And finally I would also like a way to skip the checksum check, for instance when trying a variant of a release which therefore has a different URL and contents but yet I want to reuse the existing definition.
For example this can be useful if I want to try the CE build instead of GFTC build of truffleruby …
=> Add RUBY_BUILD_TARBALL_OVERRIDE to override the ruby tarball URL

bin/ruby-build
Reuse original `build_package_copy` instead of having to maintain an additional `build_package_copy_to` step.
As a bonus, this prevents a global variable `to` from leaking.
=> Cleanup in truffleruby+graalvm installation

bin/ruby-build
Same with linking libyaml and checking for `--disable-shared`. This considers all user configuration inputs when checking for existing flags.
Fixes:
```sh
ruby-build <version> <destination> -- --disable-shared --with-openssl-dir="..." --with-libyaml-dir="..."
```
Followup to https://github.com/rbenv/ruby-build/pull/2267
=> Avoid compiling OpenSSL if the user supplied `--with-openssl-dir` on the command line

bin/ruby-build
- The `make -j 1` workaround seems neither in effect nor necessary anymore
- Assume that KERNEL_BITS workaround isn't necessary anymore
- Declare more variables as local
Ref. 959e5cb22b19621b79c2236a62e636957dcac180
=> Cleanup in OpenSSL compilation step

bin/ruby-build
LC_CTYPE is "utf-8" on macOS, which instructs utilities like `tr` to expect Unicode input. However, in case of binary files, which we here explicitly guard against, the utility will fail because of invalid input encoding.
The solution is to set LC_CTYPE=C which effectively removes the expectation around input encoding and allows `tr` to process the input byte-by-byte.
Fixes https://github.com/rbenv/ruby-build/issues/2279
=> Fix fixing JRuby shebangs on macOS

share/ruby-build/2.7.0, share/ruby-build/2.7.1, share/ruby-build/2.7.2, share/ruby-build/2.7.3, share/ruby-build/2.7.4, share/ruby-build/2.7.5, share/ruby-build/2.7.6, share/ruby-build/2.7.7
=> Unmark Ruby 2.7 as soon-to-be-EOL since it's already EOL

bin/ruby-build, share/ruby-build/maglev-1.0.0, share/ruby-build/maglev-1.1.0-dev, share/ruby-build/maglev-2.0.0-dev
Neither project has seen releases in the last 10 years, so I'm making a call that there is no strong reason for ruby-build to support them.
Ref. #278 https://github.com/rbenv/ruby-build/pull/1420
=> Remove Topaz, Maglev

bin/ruby-build, test/build.bats, test/cache.bats, test/checksum.bats, test/compiler.bats, test/fetch.bats, test/mirror.bats, test/test_helper.bash
I've always imagined that ruby-build could print the external commands executed, such as `./configure` (with full arguments list), `make`, and `make install` in most cases. This experimental branch attempts to achieve just that, while at the same time cleaning up old ruby-build code that uses so much shell redirection (e.g. `>&4 2>&1`) that it's hard to figure out which output goes where at a given point in the code.
The goal of this work would be improved user experience: hopefully, the printed commands would make it more clear as to what ruby-build does, and more importantly, what it _doesn't_ do. Feedback welcome! 🙏 
Here is the current output (note the `===>` markers):
```
$ bin/ruby-build 3.2.2 /tmp/ruby-test
To follow progress, use 'tail -f …
```
=> Restructure console output

bin/ruby-build, test/output.bats
Do not blindly try to substitute an empty string with "$TMPDIR" 🤦 
Fixes #2299
=> Fix commands printed when TMPDIR is empty

bin/ruby-build
It seems like there exist platforms that have wget which does not support the `--show-progress` option. This reverts to using wget in its default verbose mode where a progress bar and bunch more information are printed to stderr.
Fixes https://github.com/rbenv/ruby-build/issues/2301
Followup to https://github.com/rbenv/ruby-build/pull/2230
```
-> wget -O ruby-3.2.2.tar.gz https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz
--2023-11-08 23:59:46--  https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz
Resolving cache.ruby-lang.org (cache.ruby-lang.org)... 151.101.193.178, 151.101.1.178, 151.101.65.178, ...
Connecting to cache.ruby-lang.org (cache.ruby-lang.org)|151.101.193.178|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20467023 (20M) …
```
=> Abandon using `--show-progress` for wget

share/ruby-build/3.0.0, share/ruby-build/3.0.0-preview1, share/ruby-build/3.0.0-preview2, share/ruby-build/3.0.0-rc1, share/ruby-build/3.0.1, share/ruby-build/3.0.2, share/ruby-build/3.0.3, share/ruby-build/3.0.4, share/ruby-build/3.0.5, share/ruby-build/3.0.6
It reaches EOL status in March 2024.
=> Mark Ruby 3.0.x as unsupported

script/update-eol
The script will automatically assign "warn_unsupported" or "warn_eol" labels to CRuby definition files based on the information from endoflife.date.
Benefits:
- Never having to do this manually again
- Not prone to human error (unless there is a bug in my script)
TODO:
=> Add script to update `warn_unsuppported`, `warn_eol` labels

share/ruby-build/ruby-dev
* Currently the same as 3.3.0-dev but that name changes every year, so this makes it easy to install ruby dev/master.
I always wondered why this is missing, well, let's add it.
cc @nirvdrum who mentioned there is some non-trivial workaround at Shopify due to the lack of this.
=> Add ruby-dev definition

share/ruby-build/3.3.0-preview3, share/ruby-build/ruby-dev
=> Remove deprecated verify_openssl step from build definitions

bin/ruby-build, share/ruby-build/2.2.0-dev, share/ruby-build/2.3.0-dev, share/ruby-build/2.4.0-dev, share/ruby-build/2.5.0-dev, share/ruby-build/2.6.0-dev, share/ruby-build/2.7.0-dev, share/ruby-build/3.0.0-dev, share/ruby-build/3.1.0-dev, share/ruby-build/3.2.0-dev, share/ruby-build/3.3.0-dev, share/ruby-build/ruby-dev, test/build.bats
This merges "standard_build" and "standard_install" build steps into one again and defines a "standard_install_with_bundled_gems" build step that just invokes "standard" with the addition of `update-gems` & `extract-gems`.
The goal is to have a single `standard` step again instead of maintaining it as two distinct `build_package_standard_build` and `build_package_standard_install` functions.
A runtime difference that will be a result of this change is that three separate invocations `make update-gems`, `make extract-gems`, and `make install` are now executed as one: `make update-gems extract-gems install`.
/cc @hsbt as this reverts parts of https://github.com/rbenv/ruby-build/pull/1098
=> Introduce "with_bundled_gems" build step for dev rubies and unify "standard"

share/ruby-build/3.3.0-rc1
https://www.ruby-lang.org/en/news/2023/12/11/ruby-3-3-0-rc1-released/
=> Add Ruby 3.3.0-rc1

share/ruby-build/3.3.0
This worked well on my machine.
```
$ ruby-build 3.3.0 /opt/rubies/3.3.0
==> Downloading ruby-3.3.0.tar.gz...
-> curl -q -fL -o ruby-3.3.0.tar.gz https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 21.0M  100 21.0M    0     0  21.0M      0 --:--:-- --:--:-- --:--:-- 21.0M
==> Installing ruby-3.3.0...
-> ./configure --prefix=/opt/rubies/3.3.0 --enable-shared --with-ext=openssl,psych,+
-> make -j 20
-> make install
==> Installed ruby-3.3.0 to /opt/rubies/3.3.0
$ /opt/rubies/3.3.0/bin/ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
```
=> Add Ruby 3.3.0

share/ruby-build/3.3.0-dev
I will add `3.4-dev` definition after Matz update `ruby/ruby` version to `3.4.0dev`
=> Switch 3.3.0-dev to ruby_3_3 branch

share/ruby-build/3.4-dev
We should use `X.Y-dev` version instead of `X.Y.0-dev` version from Ruby 3.3 release.
=> Added 3.4-dev definition

bin/ruby-build, test/build.bats
Apparently, `--with-readline-dir` is no longer needed starting from Ruby 3.3.0. It doesn't seem harmful to pass it, but since it might cause confusion to see the implicit value being passed as part of ruby-build output, it might be a good idea to only conditionally pass it for older rubies.
Fixes https://github.com/rbenv/ruby-build/issues/2330
=> Skip passing `--with-readline-dir` for Ruby 3.3+

share/ruby-build/3.2.3
https://www.ruby-lang.org/en/news/2024/01/18/ruby-3-2-3-released/
```
SIZE: 20577155
SHA1: 7f553e514cb42751a61c3a560a7e8d727c6931ca
SHA256: af7f1757d9ddb630345988139211f1fd570ff5ba830def1cc7c468ae9b65c9ba
SHA512: 75aecd9cf87f1fa66b24ecda8837a53162071b4f8801dcfd79119a24c6e81df3e3e2ba478e1cc48c60103dfaab12a00cfa2039a621f8651298eba8bd8d576360
```
=> Add Ruby 3.2.3

share/ruby-build/truffleruby+graalvm-dev
* See https://github.com/graalvm/graal-languages-ea-builds
* These are based on Oracle GraalVM.
* cc @nirvdrum
=> Switch to EA builds from graalvm/graal-languages-ea-builds for truffleruby+graalvm-dev

bin/ruby-build, share/ruby-build/truffleruby+graalvm-dev
The `http get <url> <destfile>` utility had a bug with aria2c downloader where it couldn't properly save to destfile if it was an absolute path.
I have tried having `http get <url> -` consistently print the downloaded file to stdout, but this conflicted with the output of `log_command` (which is also to stdout) so for now let's keep using the temporary file to resolve manual URL redirects.
Followup to https://github.com/rbenv/ruby-build/pull/2356 /cc @rwstauner
=> Simplify `truffleruby+graalvm-dev` build definition re: download redirect

bin/rbenv-install, bin/rbenv-uninstall
Fixes https://github.com/rbenv/ruby-build/issues/2374
=> rbenv install: error out instead of prompting in non-interactive mode

share/ruby-build/3.0.7
This one was missed in https://github.com/rbenv/ruby-build/pull/2307 or was added after, hopefully this removes ruby 3.0.7 from `rbenv install -l` unless you list-all
=> Mark Ruby 3.0.7 as unsupported

share/ruby-build/3.0.0, share/ruby-build/3.0.0-preview1, share/ruby-build/3.0.0-preview2, share/ruby-build/3.0.0-rc1, share/ruby-build/3.0.1, share/ruby-build/3.0.2, share/ruby-build/3.0.3, share/ruby-build/3.0.4, share/ruby-build/3.0.5, share/ruby-build/3.0.6, share/ruby-build/3.0.7
Ruby 3.0 reached End of Life on 23 Apr 2024.
Changeset generated with `script/update-eol`
Followup to https://github.com/rbenv/ruby-build/pull/2307
=> Mark Ruby 3.0 as EOL

share/ruby-build/3.3.2
https://www.ruby-lang.org/en/news/2024/05/30/ruby-3-3-2-released/
=> Add Ruby 3.3.2

share/ruby-build/3.1.6
https://www.ruby-lang.org/en/news/2024/05/29/ruby-3-1-6-released/
=> Add CRuby release 3.1.6

share/ruby-build/3.1.6
There is an extra quote and it was causing a failure:
```
/home/vscode/.rbenv/plugins/ruby-build/share/ruby-build/3.1.6: line 2: unexpected EOF while looking for matching `"'
```
=> Fix 3.1.6 version definition

README.md
The RUBY_BUILD_ROOT itself does not default to share/ruby-build/ but rather must point to a directory that has definitions under `share/ruby-build/`.
The misleading verbiage was introduced: https://github.com/rbenv/ruby-build/commit/af2df4e74a305e4018331531e43e5d9276bb6875
Original phrasing introduced: https://github.com/rbenv/ruby-build/commit/ff75ca72045ce54b4c47d1b5c51e3d921cc63c96
Could still use some rephrasing I think. It's awkward to explain the env var must point to a directory that itself contains a particular path; without implying that the env var itself contains the "share/ruby-build/" path.
fixes #2391
=> Clarify RUBY_BUILD_ROOT env var

share/ruby-build/3.1-dev, share/ruby-build/3.1.0, share/ruby-build/3.1.0-preview1, share/ruby-build/3.1.1, share/ruby-build/3.1.2, share/ruby-build/3.1.3, share/ruby-build/3.1.4, share/ruby-build/3.1.5, share/ruby-build/3.1.6, share/ruby-build/3.2-dev, share/ruby-build/3.2.0, share/ruby-build/3.2.0-preview1, share/ruby-build/3.2.0-preview2, share/ruby-build/3.2.0-preview3, share/ruby-build/3.2.0-rc1, share/ruby-build/3.2.1, share/ruby-build/3.2.2, share/ruby-build/3.2.3, share/ruby-build/3.2.4, share/ruby-build/3.3-dev, share/ruby-build/3.3.0, share/ruby-build/3.3.0-preview1, share/ruby-build/3.3.0-preview2, share/ruby-build/3.3.0-preview3, share/ruby-build/3.3.0-rc1, share/ruby-build/3.3.1, share/ruby-build/3.3.2, share/ruby-build/3.4-dev, share/ruby-build/3.4.0-preview1, share/ruby-build/ruby-dev
Followup to https://github.com/rbenv/ruby-build/pull/2407
@hsbt There was a small renaming issue. I've used `script/update-openssl 3.0.14 <SHA>` to fix it.
=> Fix package name for openssl-3.0.14

share/ruby-build/3.3.3
https://www.ruby-lang.org/en/news/2024/06/12/ruby-3-3-3-released/
=> Add Ruby 3.3.3

share/ruby-build/3.3.4
This pull request adds Ruby 3.3.4 to ruby-build.
* Ruby 3.3.4 Released
https://www.ruby-lang.org/en/news/2024/07/09/ruby-3-3-4-released/
This commit works in my Ubuntu 24.04 environment as follows.
```ruby
$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
$ ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
$
```
=> Add Ruby 3.3.4

share/ruby-build/3.2.5
* Ruby 3.2.5 Released
https://www.ruby-lang.org/en/news/2024/07/26/ruby-3-2-5-released/
=> Add Ruby 3.2.5

bin/ruby-build
This resolves additional issues when tr is called in a shell that has set LC_ALL to a specific encoding. In that case, the tr may fail to ignore binary files, expecting that they are in some encoding.
See https://github.com/rbenv/ruby-build/issues/2279
=> Clear LC_ALL for tr call

.github/workflows/update-ruby.yml, script/update-cruby
Background:
I and release manager of Ruby improve release workflow recently. I make this manual workflow to automated workflow. 
After Ruby release, https://github.com/ruby/ruby/pull/11286 notify to related repositories like docker image, snap package and etc.
I would like to create new definition of ruby-build with above notification. This PR makes it with repository_dispatch feature. After that, we can update definition with simple REST call like:
```
curl -L -X POST \
-H "Authorization: Bearer xxx" \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/rbenv/ruby-build/dispatches \
-d '{"event_type": "update-ruby", "client_payload":{"ruby_version":"3.3.4", "openssl_version":"3.0.14"}}'
```
=> Auto update Ruby definition with Ruby releases

script/update-cruby
Followed up https://github.com/rbenv/ruby-build/pull/2440#issuecomment-2327746355
=> Use GitHub instead of openssl.org

bin/ruby-build, share/man/man1/ruby-build.1, share/man/man1/ruby-build.1.adoc, test/build.bats
* Similar to ruby-install's -r, --rubies-dir flag.
So this enables for example:
```
$ ruby-build -d truffleruby+graalvm-24.1.0 ~/.rubies
...
==> Installed truffleruby+graalvm-24.1.0 to /home/eregon/.rubies/truffleruby+graalvm-24.1.0
```
Which I find quite convenient compared to having to copy-paste the definition names after the rubies directory.
=> Add -d, --dir option to install to <prefix>/<definition> instead of <prefix>

README.md, bin/ruby-build, share/man/man1/ruby-build.1, share/man/man1/ruby-build.1.adoc, test/build.bats
* By searching a X.Y.Z definition if no ruby-X.Y.Z definition is not found.
So this enables for example:
```
$ ruby-build ruby-3.3.5 PREFIX
```
And with https://github.com/rbenv/ruby-build/pull/2447 it enables:
```
$ ruby-build -d ruby-3.3.4 ~/.rubies
...
==> Installed ruby-3.3.4 to /home/eregon/.rubies/ruby-3.3.4
```
It would remove the need for https://github.com/ruby/ruby-builder/blob/135bc7c215df24a672d0735189aafc510923d380/.github/workflows/build.yml#L67-L74 and likely other places working around the "asymmetry" that CRuby definitions don't have a prefix.
=> Support `ruby-build ruby-X.Y.Z DIR`

share/ruby-build/2.4-dev, share/ruby-build/2.5-dev, share/ruby-build/2.6-dev, share/ruby-build/2.7-dev, share/ruby-build/3.0-dev, share/ruby-build/3.1-dev, share/ruby-build/3.2-dev, share/ruby-build/3.3-dev, share/ruby-build/3.4-dev, share/ruby-build/ruby-dev, test/build.bats
* Only from Ruby 2.4+ since older releases don't use --enable-shared by default.
* As with releases it can be disabled by setting RUBY_CONFIGURE_OPTS=--disable-shared.
But since `--enable-shared` is currently broken on master we should wait https://bugs.ruby-lang.org/issues/20783 to be fixed before merging this.
=> Use --enable-shared for dev builds too, not only for releases

bin/ruby-build, test/build.bats
On 64-bit systems, the build system for OpenSSL tends to produce a "lib64" directory instead of a "lib" directory due to its "multilib" feature being enabled by default. However, the Ruby "openssl" extension assumes that the directory is always named "lib", or explicitly passed via `--with-openssl-lib`.
This disables multilib support in OpenSSL by passing `--libdir=lib` to OpenSSL configure step.
Reported in https://github.com/rbenv/ruby-build/discussions/2376
=> Fix linking to vendored OpenSSL on 64-bit systems

bin/ruby-build
If none of Homebrew OpenSSL versions satisfy the `needs_openssl` requirement, array iteration will reach `index=-1` and that will raise a non-fatal error when accessing the `versions` array. This makes sure not to go past index=0.
Fixes https://github.com/rbenv/ruby-build/issues/2455
=> Avoid array subscript error when checking OpenSSL versions

bin/ruby-build
Allow ruby-build to read a build definition from a named pipe in addition to just from regular files.
Example:
```
ruby-build <(echo "...") /path/to/ruby
```
=> Allow named pipes as build definition argument

README.md
The previous docs would make users think only a few Ruby versions were available.
=> Clarify --list and --definitions in the README

README.md
Otherwise `gem install` and `bundle install` (without `--path`) won't work without `sudo`. In fact the previous example install command wouldn't work at all without `sudo`.
=> Suggest to install rubies in a user-writable directory in the README

README.md, bin/ruby-build
* This is useful when one wants to avoid depending e.g. on which openssl version is installed in Homebrew, notably for https://github.com/ruby/setup-ruby/issues/668
=> Add an environment variable to always build openssl/libssl

share/ruby-build/3.1.0, share/ruby-build/3.1.0-preview1, share/ruby-build/3.1.1, share/ruby-build/3.1.2, share/ruby-build/3.1.3, share/ruby-build/3.1.4, share/ruby-build/3.1.5, share/ruby-build/3.1.6
Generated with `script/update-eol`
=> Warn that Ruby 3.1 support ends in less than 6 months

.github/workflows/update-ruby.yml
Ensures that the command fails when an HTTP error (e.g., 404) occurs.
=> Add `-f` flag to curl for HTTP error handling

bin/ruby-build, test/build.bats
When a vendored OpenSSL is needed for compiling Ruby, that OpenSSL installation ends up with its `bin/openssl` executable broken due to not finding "libssl.so" and "libcrypto.so" in the global load path for libraries. This doesn't seem to negatively affect the Ruby "openssl" extension at runtime, but does constitute a broken OpenSSL installation nevertheless.
This change causes the `bin/openssl` executable and related shared libraries to be built with an "RPATH" pointing to the "lib" directory of the vendored OpenSSL. See https://wiki.openssl.org/index.php/Compilation_and_Installation#Using_RPATHs
Fixes #2488
=> Fix library lookup path in the vendored OpenSSL

bin/ruby-build, test/build.bats
The recent rpath argument addition broke compilation of OpenSSL with clang since it seems expect this syntax (comma instead of "="):
-Wl,-rpath,<path>
Also, it doesn't seem that the rpath argument is necessary for any platform other than "Linux"; that is, we should skip passing it on BSD and macOS.
Thanks @jeremy https://github.com/rbenv/ruby-build/pull/2493#pullrequestreview-2550800730
=> Fix installing OpenSSL on non-Linux or with clang

test/stubs/stub, test/test_helper.bash
The `stub`/`unstub` test helpers are unfortunately opaque as both are undocumented, and when stubbing fails for some reason, determining why is left as a guessing/debugging exercise. This was a time-sink for myself on many an occasion.
This improves the `unstub <PROGRAM>` helper output with the following features:
- If the number of PROGRAM invocations was fewer than the number of stubbed (i.e. expected) arguments, it now prints `expected X invocations, got Y` to stderr;
- If PROGRAM got invoked but `unstub PROGRAM` still failed, it was likely that some of the invocations didn't match the stubbed ones. However, the human reading the test output has no insight into which invocations actually happened. The unstub helper now prints:
re-run test with <PROGRAM>_STUB_DEBUG=3 to log `<PROGRAM>' …
=> Improve test output for failed stubs

test/rbenv.bats
Currently, this test fails if Homebrew isn't present as it expects a
Homebrew-specific output. This commit varies the expected output based
on whether Homebrew is installed.
This patch was originally created for the Debian package for ruby-build:
https://salsa.debian.org/ruby-team/ruby-build/-/blob/607093e5198cc75ffa8e9a3b551843be5f2f6d93/debian/patches/0001-Fix-nonexistent-version-test-to-work-regardless-of-e.patch
=> Allow "nonexistent version" test to work without brew

bin/rbenv-install, test/rbenv.bats
Depending on bash version, the expression `${var/$HOME\//~/}` will not have effect because the "~" character in the replacement expression is expanded.
The updated approach is a bit of a mouthful, but it avoids using "~" in a substitution pattern, while also guarding against values of HOME that are blank or when HOME is literally just "/".
=> rbenv install: fix substituting $HOME with "~"

bin/ruby-build
When computing the SHA-2 checksum, `openssl dgst` is a potential candidate if openssl was found in PATH. Previously, openssl from Homebrew would also get explicitly added to the candidates list because, historically, Homebrew did not link it to PATH, OS X Leopard did not have `shasum`, and `/usr/bin/openssl` could not calculate sha256 checksums.
This drops support for OS X Leopard, which last had an update 15 years ago.
Ref. b396ad7cd13cc02015a006326837fbfe279e174c
=> compute_sha2: drop support for OS X Leopard

bin/ruby-build, test/test_helper.bash
JRuby does not require `$JAVA_HOME/bin` to be part of `$PATH`, therefore we should test java version with `$JAVA_HOME/bin/java -version` when `$JAVA_HOME` is defined.
See: https://github.com/ruby/ruby-builder/pull/22#issuecomment-2814646152
=> Honor `$JAVA_HOME` in `require_java`

share/ruby-build/truffleruby-dev
The latest release no longer includes 20.04
https://github.com/ruby/truffleruby-dev-builder/releases/tag/v20250424.114841
=> Update truffleruby-dev to use newer ubuntu download

share/ruby-build/jruby-10.0.0.1, share/ruby-build/jruby-9.4.12.1
This adds JRuby 10.0.0.1 and 9.4.12.1, which include the jruby-openssl fix for https://github.com/jruby/jruby-openssl/security/advisories/GHSA-72qj-48g4-5xgx.
=> Add JRuby 10.0.0.1 and 9.4.12.1

script/update-jruby
Any jruby version starting with `10.*` will have `require_java 21` instead of `require_java 8`.
/cc @headius https://github.com/rbenv/ruby-build/pull/2530#discussion_r2078079546
=> Modify `update-jruby` script to require Java 21+ for JRuby 10+

share/ruby-build/3.1.0, share/ruby-build/3.1.0-preview1, share/ruby-build/3.1.1, share/ruby-build/3.1.2, share/ruby-build/3.1.3, share/ruby-build/3.1.4, share/ruby-build/3.1.5, share/ruby-build/3.1.6, share/ruby-build/3.1.7
Ruby 3.1 reached End of Life on 26 March 2025
(Commit modelled after https://github.com/rbenv/ruby-build/commit/4bfc2e68a438f50e4285f7fb16150d51ea4cc441)
=> Mark Ruby 3.1 as EOL

README.md
Add examples of passing a custom build definition file in place of a 'known' ruby version. This is meant to more clearly document how users might use a custom build definition for a recently-released ruby that is not yet bundled in ruby-build.
This is primarily intended as a piece of documentation we can point to in Issues, wiki or to downstream tooling (like asdf-ruby) for how to use ruby-build to install additional builds of ruby. My _hope_ is that with a few examples, more folks self-service with _just-released_ rubies.
Additionally, document in the readme how to use `RUBY_BUILD_DEFINITIONS` path environment variable to provide a _collection_ of custom build definitions. This is meant to give guidance on how an organization might share multiple custom build definitions, or downstream …
=> Document examples of using custom defs

bin/ruby-build, test/build.bats
This happens while compiling OpenSSL or any other non-Ruby package:
ruby-build: line 723: [: : integer expression expected
This was because $ruby_semver was checked as a numeric value but was never set.
Fixes https://github.com/rbenv/ruby-build/issues/2572
Followup to https://github.com/rbenv/ruby-build/pull/2543
=> Fixes "integer expression expected" error
